
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Billing` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Billing
 * 
 */
export type BillingModel = runtime.Types.Result.DefaultSelection<Prisma.$BillingPayload>

export type AggregateBilling = {
  _count: BillingCountAggregateOutputType | null
  _avg: BillingAvgAggregateOutputType | null
  _sum: BillingSumAggregateOutputType | null
  _min: BillingMinAggregateOutputType | null
  _max: BillingMaxAggregateOutputType | null
}

export type BillingAvgAggregateOutputType = {
  billingID: number | null
  userID: number | null
  propertyId: number | null
  totalRent: number | null
  totalWater: number | null
  totalElectric: number | null
}

export type BillingSumAggregateOutputType = {
  billingID: number | null
  userID: number | null
  propertyId: number | null
  totalRent: number | null
  totalWater: number | null
  totalElectric: number | null
}

export type BillingMinAggregateOutputType = {
  billingID: number | null
  userID: number | null
  propertyId: number | null
  totalRent: number | null
  totalWater: number | null
  totalElectric: number | null
  dateIssued: Date | null
}

export type BillingMaxAggregateOutputType = {
  billingID: number | null
  userID: number | null
  propertyId: number | null
  totalRent: number | null
  totalWater: number | null
  totalElectric: number | null
  dateIssued: Date | null
}

export type BillingCountAggregateOutputType = {
  billingID: number
  userID: number
  propertyId: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued: number
  _all: number
}


export type BillingAvgAggregateInputType = {
  billingID?: true
  userID?: true
  propertyId?: true
  totalRent?: true
  totalWater?: true
  totalElectric?: true
}

export type BillingSumAggregateInputType = {
  billingID?: true
  userID?: true
  propertyId?: true
  totalRent?: true
  totalWater?: true
  totalElectric?: true
}

export type BillingMinAggregateInputType = {
  billingID?: true
  userID?: true
  propertyId?: true
  totalRent?: true
  totalWater?: true
  totalElectric?: true
  dateIssued?: true
}

export type BillingMaxAggregateInputType = {
  billingID?: true
  userID?: true
  propertyId?: true
  totalRent?: true
  totalWater?: true
  totalElectric?: true
  dateIssued?: true
}

export type BillingCountAggregateInputType = {
  billingID?: true
  userID?: true
  propertyId?: true
  totalRent?: true
  totalWater?: true
  totalElectric?: true
  dateIssued?: true
  _all?: true
}

export type BillingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Billing to aggregate.
   */
  where?: Prisma.BillingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Billings to fetch.
   */
  orderBy?: Prisma.BillingOrderByWithRelationInput | Prisma.BillingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BillingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Billings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Billings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Billings
  **/
  _count?: true | BillingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BillingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BillingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BillingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BillingMaxAggregateInputType
}

export type GetBillingAggregateType<T extends BillingAggregateArgs> = {
      [P in keyof T & keyof AggregateBilling]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBilling[P]>
    : Prisma.GetScalarType<T[P], AggregateBilling[P]>
}




export type BillingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BillingWhereInput
  orderBy?: Prisma.BillingOrderByWithAggregationInput | Prisma.BillingOrderByWithAggregationInput[]
  by: Prisma.BillingScalarFieldEnum[] | Prisma.BillingScalarFieldEnum
  having?: Prisma.BillingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BillingCountAggregateInputType | true
  _avg?: BillingAvgAggregateInputType
  _sum?: BillingSumAggregateInputType
  _min?: BillingMinAggregateInputType
  _max?: BillingMaxAggregateInputType
}

export type BillingGroupByOutputType = {
  billingID: number
  userID: number
  propertyId: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued: Date
  _count: BillingCountAggregateOutputType | null
  _avg: BillingAvgAggregateOutputType | null
  _sum: BillingSumAggregateOutputType | null
  _min: BillingMinAggregateOutputType | null
  _max: BillingMaxAggregateOutputType | null
}

type GetBillingGroupByPayload<T extends BillingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BillingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BillingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BillingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BillingGroupByOutputType[P]>
      }
    >
  >



export type BillingWhereInput = {
  AND?: Prisma.BillingWhereInput | Prisma.BillingWhereInput[]
  OR?: Prisma.BillingWhereInput[]
  NOT?: Prisma.BillingWhereInput | Prisma.BillingWhereInput[]
  billingID?: Prisma.IntFilter<"Billing"> | number
  userID?: Prisma.IntFilter<"Billing"> | number
  propertyId?: Prisma.IntFilter<"Billing"> | number
  totalRent?: Prisma.FloatFilter<"Billing"> | number
  totalWater?: Prisma.FloatFilter<"Billing"> | number
  totalElectric?: Prisma.FloatFilter<"Billing"> | number
  dateIssued?: Prisma.DateTimeFilter<"Billing"> | Date | string
  user?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
}

export type BillingOrderByWithRelationInput = {
  billingID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  totalRent?: Prisma.SortOrder
  totalWater?: Prisma.SortOrder
  totalElectric?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
  user?: Prisma.UsersOrderByWithRelationInput
  property?: Prisma.PropertyOrderByWithRelationInput
}

export type BillingWhereUniqueInput = Prisma.AtLeast<{
  billingID?: number
  AND?: Prisma.BillingWhereInput | Prisma.BillingWhereInput[]
  OR?: Prisma.BillingWhereInput[]
  NOT?: Prisma.BillingWhereInput | Prisma.BillingWhereInput[]
  userID?: Prisma.IntFilter<"Billing"> | number
  propertyId?: Prisma.IntFilter<"Billing"> | number
  totalRent?: Prisma.FloatFilter<"Billing"> | number
  totalWater?: Prisma.FloatFilter<"Billing"> | number
  totalElectric?: Prisma.FloatFilter<"Billing"> | number
  dateIssued?: Prisma.DateTimeFilter<"Billing"> | Date | string
  user?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
}, "billingID">

export type BillingOrderByWithAggregationInput = {
  billingID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  totalRent?: Prisma.SortOrder
  totalWater?: Prisma.SortOrder
  totalElectric?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
  _count?: Prisma.BillingCountOrderByAggregateInput
  _avg?: Prisma.BillingAvgOrderByAggregateInput
  _max?: Prisma.BillingMaxOrderByAggregateInput
  _min?: Prisma.BillingMinOrderByAggregateInput
  _sum?: Prisma.BillingSumOrderByAggregateInput
}

export type BillingScalarWhereWithAggregatesInput = {
  AND?: Prisma.BillingScalarWhereWithAggregatesInput | Prisma.BillingScalarWhereWithAggregatesInput[]
  OR?: Prisma.BillingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BillingScalarWhereWithAggregatesInput | Prisma.BillingScalarWhereWithAggregatesInput[]
  billingID?: Prisma.IntWithAggregatesFilter<"Billing"> | number
  userID?: Prisma.IntWithAggregatesFilter<"Billing"> | number
  propertyId?: Prisma.IntWithAggregatesFilter<"Billing"> | number
  totalRent?: Prisma.FloatWithAggregatesFilter<"Billing"> | number
  totalWater?: Prisma.FloatWithAggregatesFilter<"Billing"> | number
  totalElectric?: Prisma.FloatWithAggregatesFilter<"Billing"> | number
  dateIssued?: Prisma.DateTimeWithAggregatesFilter<"Billing"> | Date | string
}

export type BillingCreateInput = {
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
  user: Prisma.UsersCreateNestedOneWithoutBillingsInput
  property: Prisma.PropertyCreateNestedOneWithoutBillingsInput
}

export type BillingUncheckedCreateInput = {
  billingID?: number
  userID: number
  propertyId: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
}

export type BillingUpdateInput = {
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UsersUpdateOneRequiredWithoutBillingsNestedInput
  property?: Prisma.PropertyUpdateOneRequiredWithoutBillingsNestedInput
}

export type BillingUncheckedUpdateInput = {
  billingID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BillingCreateManyInput = {
  billingID?: number
  userID: number
  propertyId: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
}

export type BillingUpdateManyMutationInput = {
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BillingUncheckedUpdateManyInput = {
  billingID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BillingListRelationFilter = {
  every?: Prisma.BillingWhereInput
  some?: Prisma.BillingWhereInput
  none?: Prisma.BillingWhereInput
}

export type BillingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BillingCountOrderByAggregateInput = {
  billingID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  totalRent?: Prisma.SortOrder
  totalWater?: Prisma.SortOrder
  totalElectric?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
}

export type BillingAvgOrderByAggregateInput = {
  billingID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  totalRent?: Prisma.SortOrder
  totalWater?: Prisma.SortOrder
  totalElectric?: Prisma.SortOrder
}

export type BillingMaxOrderByAggregateInput = {
  billingID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  totalRent?: Prisma.SortOrder
  totalWater?: Prisma.SortOrder
  totalElectric?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
}

export type BillingMinOrderByAggregateInput = {
  billingID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  totalRent?: Prisma.SortOrder
  totalWater?: Prisma.SortOrder
  totalElectric?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
}

export type BillingSumOrderByAggregateInput = {
  billingID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  totalRent?: Prisma.SortOrder
  totalWater?: Prisma.SortOrder
  totalElectric?: Prisma.SortOrder
}

export type BillingCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutUserInput, Prisma.BillingUncheckedCreateWithoutUserInput> | Prisma.BillingCreateWithoutUserInput[] | Prisma.BillingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutUserInput | Prisma.BillingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BillingCreateManyUserInputEnvelope
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
}

export type BillingUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutUserInput, Prisma.BillingUncheckedCreateWithoutUserInput> | Prisma.BillingCreateWithoutUserInput[] | Prisma.BillingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutUserInput | Prisma.BillingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BillingCreateManyUserInputEnvelope
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
}

export type BillingUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutUserInput, Prisma.BillingUncheckedCreateWithoutUserInput> | Prisma.BillingCreateWithoutUserInput[] | Prisma.BillingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutUserInput | Prisma.BillingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BillingUpsertWithWhereUniqueWithoutUserInput | Prisma.BillingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BillingCreateManyUserInputEnvelope
  set?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  disconnect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  delete?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  update?: Prisma.BillingUpdateWithWhereUniqueWithoutUserInput | Prisma.BillingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BillingUpdateManyWithWhereWithoutUserInput | Prisma.BillingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BillingScalarWhereInput | Prisma.BillingScalarWhereInput[]
}

export type BillingUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutUserInput, Prisma.BillingUncheckedCreateWithoutUserInput> | Prisma.BillingCreateWithoutUserInput[] | Prisma.BillingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutUserInput | Prisma.BillingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BillingUpsertWithWhereUniqueWithoutUserInput | Prisma.BillingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BillingCreateManyUserInputEnvelope
  set?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  disconnect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  delete?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  update?: Prisma.BillingUpdateWithWhereUniqueWithoutUserInput | Prisma.BillingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BillingUpdateManyWithWhereWithoutUserInput | Prisma.BillingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BillingScalarWhereInput | Prisma.BillingScalarWhereInput[]
}

export type BillingCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutPropertyInput, Prisma.BillingUncheckedCreateWithoutPropertyInput> | Prisma.BillingCreateWithoutPropertyInput[] | Prisma.BillingUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutPropertyInput | Prisma.BillingCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.BillingCreateManyPropertyInputEnvelope
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
}

export type BillingUncheckedCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutPropertyInput, Prisma.BillingUncheckedCreateWithoutPropertyInput> | Prisma.BillingCreateWithoutPropertyInput[] | Prisma.BillingUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutPropertyInput | Prisma.BillingCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.BillingCreateManyPropertyInputEnvelope
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
}

export type BillingUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutPropertyInput, Prisma.BillingUncheckedCreateWithoutPropertyInput> | Prisma.BillingCreateWithoutPropertyInput[] | Prisma.BillingUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutPropertyInput | Prisma.BillingCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.BillingUpsertWithWhereUniqueWithoutPropertyInput | Prisma.BillingUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.BillingCreateManyPropertyInputEnvelope
  set?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  disconnect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  delete?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  update?: Prisma.BillingUpdateWithWhereUniqueWithoutPropertyInput | Prisma.BillingUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.BillingUpdateManyWithWhereWithoutPropertyInput | Prisma.BillingUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.BillingScalarWhereInput | Prisma.BillingScalarWhereInput[]
}

export type BillingUncheckedUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.BillingCreateWithoutPropertyInput, Prisma.BillingUncheckedCreateWithoutPropertyInput> | Prisma.BillingCreateWithoutPropertyInput[] | Prisma.BillingUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.BillingCreateOrConnectWithoutPropertyInput | Prisma.BillingCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.BillingUpsertWithWhereUniqueWithoutPropertyInput | Prisma.BillingUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.BillingCreateManyPropertyInputEnvelope
  set?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  disconnect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  delete?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  connect?: Prisma.BillingWhereUniqueInput | Prisma.BillingWhereUniqueInput[]
  update?: Prisma.BillingUpdateWithWhereUniqueWithoutPropertyInput | Prisma.BillingUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.BillingUpdateManyWithWhereWithoutPropertyInput | Prisma.BillingUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.BillingScalarWhereInput | Prisma.BillingScalarWhereInput[]
}

export type BillingCreateWithoutUserInput = {
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutBillingsInput
}

export type BillingUncheckedCreateWithoutUserInput = {
  billingID?: number
  propertyId: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
}

export type BillingCreateOrConnectWithoutUserInput = {
  where: Prisma.BillingWhereUniqueInput
  create: Prisma.XOR<Prisma.BillingCreateWithoutUserInput, Prisma.BillingUncheckedCreateWithoutUserInput>
}

export type BillingCreateManyUserInputEnvelope = {
  data: Prisma.BillingCreateManyUserInput | Prisma.BillingCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BillingUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BillingWhereUniqueInput
  update: Prisma.XOR<Prisma.BillingUpdateWithoutUserInput, Prisma.BillingUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BillingCreateWithoutUserInput, Prisma.BillingUncheckedCreateWithoutUserInput>
}

export type BillingUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BillingWhereUniqueInput
  data: Prisma.XOR<Prisma.BillingUpdateWithoutUserInput, Prisma.BillingUncheckedUpdateWithoutUserInput>
}

export type BillingUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BillingScalarWhereInput
  data: Prisma.XOR<Prisma.BillingUpdateManyMutationInput, Prisma.BillingUncheckedUpdateManyWithoutUserInput>
}

export type BillingScalarWhereInput = {
  AND?: Prisma.BillingScalarWhereInput | Prisma.BillingScalarWhereInput[]
  OR?: Prisma.BillingScalarWhereInput[]
  NOT?: Prisma.BillingScalarWhereInput | Prisma.BillingScalarWhereInput[]
  billingID?: Prisma.IntFilter<"Billing"> | number
  userID?: Prisma.IntFilter<"Billing"> | number
  propertyId?: Prisma.IntFilter<"Billing"> | number
  totalRent?: Prisma.FloatFilter<"Billing"> | number
  totalWater?: Prisma.FloatFilter<"Billing"> | number
  totalElectric?: Prisma.FloatFilter<"Billing"> | number
  dateIssued?: Prisma.DateTimeFilter<"Billing"> | Date | string
}

export type BillingCreateWithoutPropertyInput = {
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
  user: Prisma.UsersCreateNestedOneWithoutBillingsInput
}

export type BillingUncheckedCreateWithoutPropertyInput = {
  billingID?: number
  userID: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
}

export type BillingCreateOrConnectWithoutPropertyInput = {
  where: Prisma.BillingWhereUniqueInput
  create: Prisma.XOR<Prisma.BillingCreateWithoutPropertyInput, Prisma.BillingUncheckedCreateWithoutPropertyInput>
}

export type BillingCreateManyPropertyInputEnvelope = {
  data: Prisma.BillingCreateManyPropertyInput | Prisma.BillingCreateManyPropertyInput[]
  skipDuplicates?: boolean
}

export type BillingUpsertWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.BillingWhereUniqueInput
  update: Prisma.XOR<Prisma.BillingUpdateWithoutPropertyInput, Prisma.BillingUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.BillingCreateWithoutPropertyInput, Prisma.BillingUncheckedCreateWithoutPropertyInput>
}

export type BillingUpdateWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.BillingWhereUniqueInput
  data: Prisma.XOR<Prisma.BillingUpdateWithoutPropertyInput, Prisma.BillingUncheckedUpdateWithoutPropertyInput>
}

export type BillingUpdateManyWithWhereWithoutPropertyInput = {
  where: Prisma.BillingScalarWhereInput
  data: Prisma.XOR<Prisma.BillingUpdateManyMutationInput, Prisma.BillingUncheckedUpdateManyWithoutPropertyInput>
}

export type BillingCreateManyUserInput = {
  billingID?: number
  propertyId: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
}

export type BillingUpdateWithoutUserInput = {
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutBillingsNestedInput
}

export type BillingUncheckedUpdateWithoutUserInput = {
  billingID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BillingUncheckedUpdateManyWithoutUserInput = {
  billingID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BillingCreateManyPropertyInput = {
  billingID?: number
  userID: number
  totalRent: number
  totalWater: number
  totalElectric: number
  dateIssued?: Date | string
}

export type BillingUpdateWithoutPropertyInput = {
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UsersUpdateOneRequiredWithoutBillingsNestedInput
}

export type BillingUncheckedUpdateWithoutPropertyInput = {
  billingID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BillingUncheckedUpdateManyWithoutPropertyInput = {
  billingID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  totalRent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalWater?: Prisma.FloatFieldUpdateOperationsInput | number
  totalElectric?: Prisma.FloatFieldUpdateOperationsInput | number
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type BillingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  billingID?: boolean
  userID?: boolean
  propertyId?: boolean
  totalRent?: boolean
  totalWater?: boolean
  totalElectric?: boolean
  dateIssued?: boolean
  user?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["billing"]>



export type BillingSelectScalar = {
  billingID?: boolean
  userID?: boolean
  propertyId?: boolean
  totalRent?: boolean
  totalWater?: boolean
  totalElectric?: boolean
  dateIssued?: boolean
}

export type BillingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"billingID" | "userID" | "propertyId" | "totalRent" | "totalWater" | "totalElectric" | "dateIssued", ExtArgs["result"]["billing"]>
export type BillingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
}

export type $BillingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Billing"
  objects: {
    user: Prisma.$UsersPayload<ExtArgs>
    property: Prisma.$PropertyPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    billingID: number
    userID: number
    propertyId: number
    totalRent: number
    totalWater: number
    totalElectric: number
    dateIssued: Date
  }, ExtArgs["result"]["billing"]>
  composites: {}
}

export type BillingGetPayload<S extends boolean | null | undefined | BillingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BillingPayload, S>

export type BillingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BillingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BillingCountAggregateInputType | true
  }

export interface BillingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Billing'], meta: { name: 'Billing' } }
  /**
   * Find zero or one Billing that matches the filter.
   * @param {BillingFindUniqueArgs} args - Arguments to find a Billing
   * @example
   * // Get one Billing
   * const billing = await prisma.billing.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BillingFindUniqueArgs>(args: Prisma.SelectSubset<T, BillingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Billing that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BillingFindUniqueOrThrowArgs} args - Arguments to find a Billing
   * @example
   * // Get one Billing
   * const billing = await prisma.billing.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BillingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BillingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Billing that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BillingFindFirstArgs} args - Arguments to find a Billing
   * @example
   * // Get one Billing
   * const billing = await prisma.billing.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BillingFindFirstArgs>(args?: Prisma.SelectSubset<T, BillingFindFirstArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Billing that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BillingFindFirstOrThrowArgs} args - Arguments to find a Billing
   * @example
   * // Get one Billing
   * const billing = await prisma.billing.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BillingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BillingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Billings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BillingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Billings
   * const billings = await prisma.billing.findMany()
   * 
   * // Get first 10 Billings
   * const billings = await prisma.billing.findMany({ take: 10 })
   * 
   * // Only select the `billingID`
   * const billingWithBillingIDOnly = await prisma.billing.findMany({ select: { billingID: true } })
   * 
   */
  findMany<T extends BillingFindManyArgs>(args?: Prisma.SelectSubset<T, BillingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Billing.
   * @param {BillingCreateArgs} args - Arguments to create a Billing.
   * @example
   * // Create one Billing
   * const Billing = await prisma.billing.create({
   *   data: {
   *     // ... data to create a Billing
   *   }
   * })
   * 
   */
  create<T extends BillingCreateArgs>(args: Prisma.SelectSubset<T, BillingCreateArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Billings.
   * @param {BillingCreateManyArgs} args - Arguments to create many Billings.
   * @example
   * // Create many Billings
   * const billing = await prisma.billing.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BillingCreateManyArgs>(args?: Prisma.SelectSubset<T, BillingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Billing.
   * @param {BillingDeleteArgs} args - Arguments to delete one Billing.
   * @example
   * // Delete one Billing
   * const Billing = await prisma.billing.delete({
   *   where: {
   *     // ... filter to delete one Billing
   *   }
   * })
   * 
   */
  delete<T extends BillingDeleteArgs>(args: Prisma.SelectSubset<T, BillingDeleteArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Billing.
   * @param {BillingUpdateArgs} args - Arguments to update one Billing.
   * @example
   * // Update one Billing
   * const billing = await prisma.billing.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BillingUpdateArgs>(args: Prisma.SelectSubset<T, BillingUpdateArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Billings.
   * @param {BillingDeleteManyArgs} args - Arguments to filter Billings to delete.
   * @example
   * // Delete a few Billings
   * const { count } = await prisma.billing.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BillingDeleteManyArgs>(args?: Prisma.SelectSubset<T, BillingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Billings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BillingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Billings
   * const billing = await prisma.billing.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BillingUpdateManyArgs>(args: Prisma.SelectSubset<T, BillingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Billing.
   * @param {BillingUpsertArgs} args - Arguments to update or create a Billing.
   * @example
   * // Update or create a Billing
   * const billing = await prisma.billing.upsert({
   *   create: {
   *     // ... data to create a Billing
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Billing we want to update
   *   }
   * })
   */
  upsert<T extends BillingUpsertArgs>(args: Prisma.SelectSubset<T, BillingUpsertArgs<ExtArgs>>): Prisma.Prisma__BillingClient<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Billings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BillingCountArgs} args - Arguments to filter Billings to count.
   * @example
   * // Count the number of Billings
   * const count = await prisma.billing.count({
   *   where: {
   *     // ... the filter for the Billings we want to count
   *   }
   * })
  **/
  count<T extends BillingCountArgs>(
    args?: Prisma.Subset<T, BillingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BillingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Billing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BillingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BillingAggregateArgs>(args: Prisma.Subset<T, BillingAggregateArgs>): Prisma.PrismaPromise<GetBillingAggregateType<T>>

  /**
   * Group by Billing.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BillingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BillingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BillingGroupByArgs['orderBy'] }
      : { orderBy?: BillingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BillingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBillingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Billing model
 */
readonly fields: BillingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Billing.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BillingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UsersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsersDefaultArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  property<T extends Prisma.PropertyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PropertyDefaultArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Billing model
 */
export interface BillingFieldRefs {
  readonly billingID: Prisma.FieldRef<"Billing", 'Int'>
  readonly userID: Prisma.FieldRef<"Billing", 'Int'>
  readonly propertyId: Prisma.FieldRef<"Billing", 'Int'>
  readonly totalRent: Prisma.FieldRef<"Billing", 'Float'>
  readonly totalWater: Prisma.FieldRef<"Billing", 'Float'>
  readonly totalElectric: Prisma.FieldRef<"Billing", 'Float'>
  readonly dateIssued: Prisma.FieldRef<"Billing", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Billing findUnique
 */
export type BillingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * Filter, which Billing to fetch.
   */
  where: Prisma.BillingWhereUniqueInput
}

/**
 * Billing findUniqueOrThrow
 */
export type BillingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * Filter, which Billing to fetch.
   */
  where: Prisma.BillingWhereUniqueInput
}

/**
 * Billing findFirst
 */
export type BillingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * Filter, which Billing to fetch.
   */
  where?: Prisma.BillingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Billings to fetch.
   */
  orderBy?: Prisma.BillingOrderByWithRelationInput | Prisma.BillingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Billings.
   */
  cursor?: Prisma.BillingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Billings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Billings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Billings.
   */
  distinct?: Prisma.BillingScalarFieldEnum | Prisma.BillingScalarFieldEnum[]
}

/**
 * Billing findFirstOrThrow
 */
export type BillingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * Filter, which Billing to fetch.
   */
  where?: Prisma.BillingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Billings to fetch.
   */
  orderBy?: Prisma.BillingOrderByWithRelationInput | Prisma.BillingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Billings.
   */
  cursor?: Prisma.BillingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Billings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Billings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Billings.
   */
  distinct?: Prisma.BillingScalarFieldEnum | Prisma.BillingScalarFieldEnum[]
}

/**
 * Billing findMany
 */
export type BillingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * Filter, which Billings to fetch.
   */
  where?: Prisma.BillingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Billings to fetch.
   */
  orderBy?: Prisma.BillingOrderByWithRelationInput | Prisma.BillingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Billings.
   */
  cursor?: Prisma.BillingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Billings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Billings.
   */
  skip?: number
  distinct?: Prisma.BillingScalarFieldEnum | Prisma.BillingScalarFieldEnum[]
}

/**
 * Billing create
 */
export type BillingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * The data needed to create a Billing.
   */
  data: Prisma.XOR<Prisma.BillingCreateInput, Prisma.BillingUncheckedCreateInput>
}

/**
 * Billing createMany
 */
export type BillingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Billings.
   */
  data: Prisma.BillingCreateManyInput | Prisma.BillingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Billing update
 */
export type BillingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * The data needed to update a Billing.
   */
  data: Prisma.XOR<Prisma.BillingUpdateInput, Prisma.BillingUncheckedUpdateInput>
  /**
   * Choose, which Billing to update.
   */
  where: Prisma.BillingWhereUniqueInput
}

/**
 * Billing updateMany
 */
export type BillingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Billings.
   */
  data: Prisma.XOR<Prisma.BillingUpdateManyMutationInput, Prisma.BillingUncheckedUpdateManyInput>
  /**
   * Filter which Billings to update
   */
  where?: Prisma.BillingWhereInput
  /**
   * Limit how many Billings to update.
   */
  limit?: number
}

/**
 * Billing upsert
 */
export type BillingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * The filter to search for the Billing to update in case it exists.
   */
  where: Prisma.BillingWhereUniqueInput
  /**
   * In case the Billing found by the `where` argument doesn't exist, create a new Billing with this data.
   */
  create: Prisma.XOR<Prisma.BillingCreateInput, Prisma.BillingUncheckedCreateInput>
  /**
   * In case the Billing was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BillingUpdateInput, Prisma.BillingUncheckedUpdateInput>
}

/**
 * Billing delete
 */
export type BillingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  /**
   * Filter which Billing to delete.
   */
  where: Prisma.BillingWhereUniqueInput
}

/**
 * Billing deleteMany
 */
export type BillingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Billings to delete
   */
  where?: Prisma.BillingWhereInput
  /**
   * Limit how many Billings to delete.
   */
  limit?: number
}

/**
 * Billing without action
 */
export type BillingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
}
