
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Maintenance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Maintenance
 * 
 */
export type MaintenanceModel = runtime.Types.Result.DefaultSelection<Prisma.$MaintenancePayload>

export type AggregateMaintenance = {
  _count: MaintenanceCountAggregateOutputType | null
  _avg: MaintenanceAvgAggregateOutputType | null
  _sum: MaintenanceSumAggregateOutputType | null
  _min: MaintenanceMinAggregateOutputType | null
  _max: MaintenanceMaxAggregateOutputType | null
}

export type MaintenanceAvgAggregateOutputType = {
  maintenanceID: number | null
  userID: number | null
  propertyId: number | null
}

export type MaintenanceSumAggregateOutputType = {
  maintenanceID: number | null
  userID: number | null
  propertyId: number | null
}

export type MaintenanceMinAggregateOutputType = {
  maintenanceID: number | null
  userID: number | null
  propertyId: number | null
  rawRequest: string | null
  processedRequest: string | null
  status: string | null
  schedule: Date | null
  dateIssued: Date | null
}

export type MaintenanceMaxAggregateOutputType = {
  maintenanceID: number | null
  userID: number | null
  propertyId: number | null
  rawRequest: string | null
  processedRequest: string | null
  status: string | null
  schedule: Date | null
  dateIssued: Date | null
}

export type MaintenanceCountAggregateOutputType = {
  maintenanceID: number
  userID: number
  propertyId: number
  rawRequest: number
  processedRequest: number
  status: number
  schedule: number
  dateIssued: number
  _all: number
}


export type MaintenanceAvgAggregateInputType = {
  maintenanceID?: true
  userID?: true
  propertyId?: true
}

export type MaintenanceSumAggregateInputType = {
  maintenanceID?: true
  userID?: true
  propertyId?: true
}

export type MaintenanceMinAggregateInputType = {
  maintenanceID?: true
  userID?: true
  propertyId?: true
  rawRequest?: true
  processedRequest?: true
  status?: true
  schedule?: true
  dateIssued?: true
}

export type MaintenanceMaxAggregateInputType = {
  maintenanceID?: true
  userID?: true
  propertyId?: true
  rawRequest?: true
  processedRequest?: true
  status?: true
  schedule?: true
  dateIssued?: true
}

export type MaintenanceCountAggregateInputType = {
  maintenanceID?: true
  userID?: true
  propertyId?: true
  rawRequest?: true
  processedRequest?: true
  status?: true
  schedule?: true
  dateIssued?: true
  _all?: true
}

export type MaintenanceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Maintenance to aggregate.
   */
  where?: Prisma.MaintenanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Maintenances to fetch.
   */
  orderBy?: Prisma.MaintenanceOrderByWithRelationInput | Prisma.MaintenanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MaintenanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Maintenances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Maintenances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Maintenances
  **/
  _count?: true | MaintenanceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MaintenanceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MaintenanceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MaintenanceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MaintenanceMaxAggregateInputType
}

export type GetMaintenanceAggregateType<T extends MaintenanceAggregateArgs> = {
      [P in keyof T & keyof AggregateMaintenance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMaintenance[P]>
    : Prisma.GetScalarType<T[P], AggregateMaintenance[P]>
}




export type MaintenanceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaintenanceWhereInput
  orderBy?: Prisma.MaintenanceOrderByWithAggregationInput | Prisma.MaintenanceOrderByWithAggregationInput[]
  by: Prisma.MaintenanceScalarFieldEnum[] | Prisma.MaintenanceScalarFieldEnum
  having?: Prisma.MaintenanceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MaintenanceCountAggregateInputType | true
  _avg?: MaintenanceAvgAggregateInputType
  _sum?: MaintenanceSumAggregateInputType
  _min?: MaintenanceMinAggregateInputType
  _max?: MaintenanceMaxAggregateInputType
}

export type MaintenanceGroupByOutputType = {
  maintenanceID: number
  userID: number
  propertyId: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule: Date | null
  dateIssued: Date
  _count: MaintenanceCountAggregateOutputType | null
  _avg: MaintenanceAvgAggregateOutputType | null
  _sum: MaintenanceSumAggregateOutputType | null
  _min: MaintenanceMinAggregateOutputType | null
  _max: MaintenanceMaxAggregateOutputType | null
}

type GetMaintenanceGroupByPayload<T extends MaintenanceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MaintenanceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MaintenanceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MaintenanceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MaintenanceGroupByOutputType[P]>
      }
    >
  >



export type MaintenanceWhereInput = {
  AND?: Prisma.MaintenanceWhereInput | Prisma.MaintenanceWhereInput[]
  OR?: Prisma.MaintenanceWhereInput[]
  NOT?: Prisma.MaintenanceWhereInput | Prisma.MaintenanceWhereInput[]
  maintenanceID?: Prisma.IntFilter<"Maintenance"> | number
  userID?: Prisma.IntFilter<"Maintenance"> | number
  propertyId?: Prisma.IntFilter<"Maintenance"> | number
  rawRequest?: Prisma.StringFilter<"Maintenance"> | string
  processedRequest?: Prisma.StringFilter<"Maintenance"> | string
  status?: Prisma.StringFilter<"Maintenance"> | string
  schedule?: Prisma.DateTimeNullableFilter<"Maintenance"> | Date | string | null
  dateIssued?: Prisma.DateTimeFilter<"Maintenance"> | Date | string
  user?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  documentations?: Prisma.DocumentationListRelationFilter
}

export type MaintenanceOrderByWithRelationInput = {
  maintenanceID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  rawRequest?: Prisma.SortOrder
  processedRequest?: Prisma.SortOrder
  status?: Prisma.SortOrder
  schedule?: Prisma.SortOrderInput | Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
  user?: Prisma.UsersOrderByWithRelationInput
  property?: Prisma.PropertyOrderByWithRelationInput
  documentations?: Prisma.DocumentationOrderByRelationAggregateInput
  _relevance?: Prisma.MaintenanceOrderByRelevanceInput
}

export type MaintenanceWhereUniqueInput = Prisma.AtLeast<{
  maintenanceID?: number
  AND?: Prisma.MaintenanceWhereInput | Prisma.MaintenanceWhereInput[]
  OR?: Prisma.MaintenanceWhereInput[]
  NOT?: Prisma.MaintenanceWhereInput | Prisma.MaintenanceWhereInput[]
  userID?: Prisma.IntFilter<"Maintenance"> | number
  propertyId?: Prisma.IntFilter<"Maintenance"> | number
  rawRequest?: Prisma.StringFilter<"Maintenance"> | string
  processedRequest?: Prisma.StringFilter<"Maintenance"> | string
  status?: Prisma.StringFilter<"Maintenance"> | string
  schedule?: Prisma.DateTimeNullableFilter<"Maintenance"> | Date | string | null
  dateIssued?: Prisma.DateTimeFilter<"Maintenance"> | Date | string
  user?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  documentations?: Prisma.DocumentationListRelationFilter
}, "maintenanceID">

export type MaintenanceOrderByWithAggregationInput = {
  maintenanceID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  rawRequest?: Prisma.SortOrder
  processedRequest?: Prisma.SortOrder
  status?: Prisma.SortOrder
  schedule?: Prisma.SortOrderInput | Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
  _count?: Prisma.MaintenanceCountOrderByAggregateInput
  _avg?: Prisma.MaintenanceAvgOrderByAggregateInput
  _max?: Prisma.MaintenanceMaxOrderByAggregateInput
  _min?: Prisma.MaintenanceMinOrderByAggregateInput
  _sum?: Prisma.MaintenanceSumOrderByAggregateInput
}

export type MaintenanceScalarWhereWithAggregatesInput = {
  AND?: Prisma.MaintenanceScalarWhereWithAggregatesInput | Prisma.MaintenanceScalarWhereWithAggregatesInput[]
  OR?: Prisma.MaintenanceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MaintenanceScalarWhereWithAggregatesInput | Prisma.MaintenanceScalarWhereWithAggregatesInput[]
  maintenanceID?: Prisma.IntWithAggregatesFilter<"Maintenance"> | number
  userID?: Prisma.IntWithAggregatesFilter<"Maintenance"> | number
  propertyId?: Prisma.IntWithAggregatesFilter<"Maintenance"> | number
  rawRequest?: Prisma.StringWithAggregatesFilter<"Maintenance"> | string
  processedRequest?: Prisma.StringWithAggregatesFilter<"Maintenance"> | string
  status?: Prisma.StringWithAggregatesFilter<"Maintenance"> | string
  schedule?: Prisma.DateTimeNullableWithAggregatesFilter<"Maintenance"> | Date | string | null
  dateIssued?: Prisma.DateTimeWithAggregatesFilter<"Maintenance"> | Date | string
}

export type MaintenanceCreateInput = {
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
  user: Prisma.UsersCreateNestedOneWithoutMaintenancesInput
  property: Prisma.PropertyCreateNestedOneWithoutMaintenancesInput
  documentations?: Prisma.DocumentationCreateNestedManyWithoutMaintenanceInput
}

export type MaintenanceUncheckedCreateInput = {
  maintenanceID?: number
  userID: number
  propertyId: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
  documentations?: Prisma.DocumentationUncheckedCreateNestedManyWithoutMaintenanceInput
}

export type MaintenanceUpdateInput = {
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UsersUpdateOneRequiredWithoutMaintenancesNestedInput
  property?: Prisma.PropertyUpdateOneRequiredWithoutMaintenancesNestedInput
  documentations?: Prisma.DocumentationUpdateManyWithoutMaintenanceNestedInput
}

export type MaintenanceUncheckedUpdateInput = {
  maintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  documentations?: Prisma.DocumentationUncheckedUpdateManyWithoutMaintenanceNestedInput
}

export type MaintenanceCreateManyInput = {
  maintenanceID?: number
  userID: number
  propertyId: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
}

export type MaintenanceUpdateManyMutationInput = {
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceUncheckedUpdateManyInput = {
  maintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceListRelationFilter = {
  every?: Prisma.MaintenanceWhereInput
  some?: Prisma.MaintenanceWhereInput
  none?: Prisma.MaintenanceWhereInput
}

export type MaintenanceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MaintenanceOrderByRelevanceInput = {
  fields: Prisma.MaintenanceOrderByRelevanceFieldEnum | Prisma.MaintenanceOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type MaintenanceCountOrderByAggregateInput = {
  maintenanceID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  rawRequest?: Prisma.SortOrder
  processedRequest?: Prisma.SortOrder
  status?: Prisma.SortOrder
  schedule?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
}

export type MaintenanceAvgOrderByAggregateInput = {
  maintenanceID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
}

export type MaintenanceMaxOrderByAggregateInput = {
  maintenanceID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  rawRequest?: Prisma.SortOrder
  processedRequest?: Prisma.SortOrder
  status?: Prisma.SortOrder
  schedule?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
}

export type MaintenanceMinOrderByAggregateInput = {
  maintenanceID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  rawRequest?: Prisma.SortOrder
  processedRequest?: Prisma.SortOrder
  status?: Prisma.SortOrder
  schedule?: Prisma.SortOrder
  dateIssued?: Prisma.SortOrder
}

export type MaintenanceSumOrderByAggregateInput = {
  maintenanceID?: Prisma.SortOrder
  userID?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
}

export type MaintenanceScalarRelationFilter = {
  is?: Prisma.MaintenanceWhereInput
  isNot?: Prisma.MaintenanceWhereInput
}

export type MaintenanceCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutUserInput, Prisma.MaintenanceUncheckedCreateWithoutUserInput> | Prisma.MaintenanceCreateWithoutUserInput[] | Prisma.MaintenanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutUserInput | Prisma.MaintenanceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MaintenanceCreateManyUserInputEnvelope
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
}

export type MaintenanceUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutUserInput, Prisma.MaintenanceUncheckedCreateWithoutUserInput> | Prisma.MaintenanceCreateWithoutUserInput[] | Prisma.MaintenanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutUserInput | Prisma.MaintenanceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.MaintenanceCreateManyUserInputEnvelope
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
}

export type MaintenanceUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutUserInput, Prisma.MaintenanceUncheckedCreateWithoutUserInput> | Prisma.MaintenanceCreateWithoutUserInput[] | Prisma.MaintenanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutUserInput | Prisma.MaintenanceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MaintenanceUpsertWithWhereUniqueWithoutUserInput | Prisma.MaintenanceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MaintenanceCreateManyUserInputEnvelope
  set?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  delete?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  update?: Prisma.MaintenanceUpdateWithWhereUniqueWithoutUserInput | Prisma.MaintenanceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MaintenanceUpdateManyWithWhereWithoutUserInput | Prisma.MaintenanceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MaintenanceScalarWhereInput | Prisma.MaintenanceScalarWhereInput[]
}

export type MaintenanceUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutUserInput, Prisma.MaintenanceUncheckedCreateWithoutUserInput> | Prisma.MaintenanceCreateWithoutUserInput[] | Prisma.MaintenanceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutUserInput | Prisma.MaintenanceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.MaintenanceUpsertWithWhereUniqueWithoutUserInput | Prisma.MaintenanceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.MaintenanceCreateManyUserInputEnvelope
  set?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  delete?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  update?: Prisma.MaintenanceUpdateWithWhereUniqueWithoutUserInput | Prisma.MaintenanceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.MaintenanceUpdateManyWithWhereWithoutUserInput | Prisma.MaintenanceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.MaintenanceScalarWhereInput | Prisma.MaintenanceScalarWhereInput[]
}

export type MaintenanceCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutPropertyInput, Prisma.MaintenanceUncheckedCreateWithoutPropertyInput> | Prisma.MaintenanceCreateWithoutPropertyInput[] | Prisma.MaintenanceUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutPropertyInput | Prisma.MaintenanceCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.MaintenanceCreateManyPropertyInputEnvelope
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
}

export type MaintenanceUncheckedCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutPropertyInput, Prisma.MaintenanceUncheckedCreateWithoutPropertyInput> | Prisma.MaintenanceCreateWithoutPropertyInput[] | Prisma.MaintenanceUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutPropertyInput | Prisma.MaintenanceCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.MaintenanceCreateManyPropertyInputEnvelope
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
}

export type MaintenanceUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutPropertyInput, Prisma.MaintenanceUncheckedCreateWithoutPropertyInput> | Prisma.MaintenanceCreateWithoutPropertyInput[] | Prisma.MaintenanceUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutPropertyInput | Prisma.MaintenanceCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.MaintenanceUpsertWithWhereUniqueWithoutPropertyInput | Prisma.MaintenanceUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.MaintenanceCreateManyPropertyInputEnvelope
  set?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  delete?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  update?: Prisma.MaintenanceUpdateWithWhereUniqueWithoutPropertyInput | Prisma.MaintenanceUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.MaintenanceUpdateManyWithWhereWithoutPropertyInput | Prisma.MaintenanceUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.MaintenanceScalarWhereInput | Prisma.MaintenanceScalarWhereInput[]
}

export type MaintenanceUncheckedUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutPropertyInput, Prisma.MaintenanceUncheckedCreateWithoutPropertyInput> | Prisma.MaintenanceCreateWithoutPropertyInput[] | Prisma.MaintenanceUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutPropertyInput | Prisma.MaintenanceCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.MaintenanceUpsertWithWhereUniqueWithoutPropertyInput | Prisma.MaintenanceUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.MaintenanceCreateManyPropertyInputEnvelope
  set?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  disconnect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  delete?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  connect?: Prisma.MaintenanceWhereUniqueInput | Prisma.MaintenanceWhereUniqueInput[]
  update?: Prisma.MaintenanceUpdateWithWhereUniqueWithoutPropertyInput | Prisma.MaintenanceUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.MaintenanceUpdateManyWithWhereWithoutPropertyInput | Prisma.MaintenanceUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.MaintenanceScalarWhereInput | Prisma.MaintenanceScalarWhereInput[]
}

export type MaintenanceCreateNestedOneWithoutDocumentationsInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutDocumentationsInput, Prisma.MaintenanceUncheckedCreateWithoutDocumentationsInput>
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutDocumentationsInput
  connect?: Prisma.MaintenanceWhereUniqueInput
}

export type MaintenanceUpdateOneRequiredWithoutDocumentationsNestedInput = {
  create?: Prisma.XOR<Prisma.MaintenanceCreateWithoutDocumentationsInput, Prisma.MaintenanceUncheckedCreateWithoutDocumentationsInput>
  connectOrCreate?: Prisma.MaintenanceCreateOrConnectWithoutDocumentationsInput
  upsert?: Prisma.MaintenanceUpsertWithoutDocumentationsInput
  connect?: Prisma.MaintenanceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MaintenanceUpdateToOneWithWhereWithoutDocumentationsInput, Prisma.MaintenanceUpdateWithoutDocumentationsInput>, Prisma.MaintenanceUncheckedUpdateWithoutDocumentationsInput>
}

export type MaintenanceCreateWithoutUserInput = {
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
  property: Prisma.PropertyCreateNestedOneWithoutMaintenancesInput
  documentations?: Prisma.DocumentationCreateNestedManyWithoutMaintenanceInput
}

export type MaintenanceUncheckedCreateWithoutUserInput = {
  maintenanceID?: number
  propertyId: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
  documentations?: Prisma.DocumentationUncheckedCreateNestedManyWithoutMaintenanceInput
}

export type MaintenanceCreateOrConnectWithoutUserInput = {
  where: Prisma.MaintenanceWhereUniqueInput
  create: Prisma.XOR<Prisma.MaintenanceCreateWithoutUserInput, Prisma.MaintenanceUncheckedCreateWithoutUserInput>
}

export type MaintenanceCreateManyUserInputEnvelope = {
  data: Prisma.MaintenanceCreateManyUserInput | Prisma.MaintenanceCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type MaintenanceUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.MaintenanceWhereUniqueInput
  update: Prisma.XOR<Prisma.MaintenanceUpdateWithoutUserInput, Prisma.MaintenanceUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.MaintenanceCreateWithoutUserInput, Prisma.MaintenanceUncheckedCreateWithoutUserInput>
}

export type MaintenanceUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.MaintenanceWhereUniqueInput
  data: Prisma.XOR<Prisma.MaintenanceUpdateWithoutUserInput, Prisma.MaintenanceUncheckedUpdateWithoutUserInput>
}

export type MaintenanceUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.MaintenanceScalarWhereInput
  data: Prisma.XOR<Prisma.MaintenanceUpdateManyMutationInput, Prisma.MaintenanceUncheckedUpdateManyWithoutUserInput>
}

export type MaintenanceScalarWhereInput = {
  AND?: Prisma.MaintenanceScalarWhereInput | Prisma.MaintenanceScalarWhereInput[]
  OR?: Prisma.MaintenanceScalarWhereInput[]
  NOT?: Prisma.MaintenanceScalarWhereInput | Prisma.MaintenanceScalarWhereInput[]
  maintenanceID?: Prisma.IntFilter<"Maintenance"> | number
  userID?: Prisma.IntFilter<"Maintenance"> | number
  propertyId?: Prisma.IntFilter<"Maintenance"> | number
  rawRequest?: Prisma.StringFilter<"Maintenance"> | string
  processedRequest?: Prisma.StringFilter<"Maintenance"> | string
  status?: Prisma.StringFilter<"Maintenance"> | string
  schedule?: Prisma.DateTimeNullableFilter<"Maintenance"> | Date | string | null
  dateIssued?: Prisma.DateTimeFilter<"Maintenance"> | Date | string
}

export type MaintenanceCreateWithoutPropertyInput = {
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
  user: Prisma.UsersCreateNestedOneWithoutMaintenancesInput
  documentations?: Prisma.DocumentationCreateNestedManyWithoutMaintenanceInput
}

export type MaintenanceUncheckedCreateWithoutPropertyInput = {
  maintenanceID?: number
  userID: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
  documentations?: Prisma.DocumentationUncheckedCreateNestedManyWithoutMaintenanceInput
}

export type MaintenanceCreateOrConnectWithoutPropertyInput = {
  where: Prisma.MaintenanceWhereUniqueInput
  create: Prisma.XOR<Prisma.MaintenanceCreateWithoutPropertyInput, Prisma.MaintenanceUncheckedCreateWithoutPropertyInput>
}

export type MaintenanceCreateManyPropertyInputEnvelope = {
  data: Prisma.MaintenanceCreateManyPropertyInput | Prisma.MaintenanceCreateManyPropertyInput[]
  skipDuplicates?: boolean
}

export type MaintenanceUpsertWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.MaintenanceWhereUniqueInput
  update: Prisma.XOR<Prisma.MaintenanceUpdateWithoutPropertyInput, Prisma.MaintenanceUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.MaintenanceCreateWithoutPropertyInput, Prisma.MaintenanceUncheckedCreateWithoutPropertyInput>
}

export type MaintenanceUpdateWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.MaintenanceWhereUniqueInput
  data: Prisma.XOR<Prisma.MaintenanceUpdateWithoutPropertyInput, Prisma.MaintenanceUncheckedUpdateWithoutPropertyInput>
}

export type MaintenanceUpdateManyWithWhereWithoutPropertyInput = {
  where: Prisma.MaintenanceScalarWhereInput
  data: Prisma.XOR<Prisma.MaintenanceUpdateManyMutationInput, Prisma.MaintenanceUncheckedUpdateManyWithoutPropertyInput>
}

export type MaintenanceCreateWithoutDocumentationsInput = {
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
  user: Prisma.UsersCreateNestedOneWithoutMaintenancesInput
  property: Prisma.PropertyCreateNestedOneWithoutMaintenancesInput
}

export type MaintenanceUncheckedCreateWithoutDocumentationsInput = {
  maintenanceID?: number
  userID: number
  propertyId: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
}

export type MaintenanceCreateOrConnectWithoutDocumentationsInput = {
  where: Prisma.MaintenanceWhereUniqueInput
  create: Prisma.XOR<Prisma.MaintenanceCreateWithoutDocumentationsInput, Prisma.MaintenanceUncheckedCreateWithoutDocumentationsInput>
}

export type MaintenanceUpsertWithoutDocumentationsInput = {
  update: Prisma.XOR<Prisma.MaintenanceUpdateWithoutDocumentationsInput, Prisma.MaintenanceUncheckedUpdateWithoutDocumentationsInput>
  create: Prisma.XOR<Prisma.MaintenanceCreateWithoutDocumentationsInput, Prisma.MaintenanceUncheckedCreateWithoutDocumentationsInput>
  where?: Prisma.MaintenanceWhereInput
}

export type MaintenanceUpdateToOneWithWhereWithoutDocumentationsInput = {
  where?: Prisma.MaintenanceWhereInput
  data: Prisma.XOR<Prisma.MaintenanceUpdateWithoutDocumentationsInput, Prisma.MaintenanceUncheckedUpdateWithoutDocumentationsInput>
}

export type MaintenanceUpdateWithoutDocumentationsInput = {
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UsersUpdateOneRequiredWithoutMaintenancesNestedInput
  property?: Prisma.PropertyUpdateOneRequiredWithoutMaintenancesNestedInput
}

export type MaintenanceUncheckedUpdateWithoutDocumentationsInput = {
  maintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceCreateManyUserInput = {
  maintenanceID?: number
  propertyId: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
}

export type MaintenanceUpdateWithoutUserInput = {
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  property?: Prisma.PropertyUpdateOneRequiredWithoutMaintenancesNestedInput
  documentations?: Prisma.DocumentationUpdateManyWithoutMaintenanceNestedInput
}

export type MaintenanceUncheckedUpdateWithoutUserInput = {
  maintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  documentations?: Prisma.DocumentationUncheckedUpdateManyWithoutMaintenanceNestedInput
}

export type MaintenanceUncheckedUpdateManyWithoutUserInput = {
  maintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MaintenanceCreateManyPropertyInput = {
  maintenanceID?: number
  userID: number
  rawRequest: string
  processedRequest: string
  status: string
  schedule?: Date | string | null
  dateIssued?: Date | string
}

export type MaintenanceUpdateWithoutPropertyInput = {
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UsersUpdateOneRequiredWithoutMaintenancesNestedInput
  documentations?: Prisma.DocumentationUpdateManyWithoutMaintenanceNestedInput
}

export type MaintenanceUncheckedUpdateWithoutPropertyInput = {
  maintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  documentations?: Prisma.DocumentationUncheckedUpdateManyWithoutMaintenanceNestedInput
}

export type MaintenanceUncheckedUpdateManyWithoutPropertyInput = {
  maintenanceID?: Prisma.IntFieldUpdateOperationsInput | number
  userID?: Prisma.IntFieldUpdateOperationsInput | number
  rawRequest?: Prisma.StringFieldUpdateOperationsInput | string
  processedRequest?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  schedule?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateIssued?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MaintenanceCountOutputType
 */

export type MaintenanceCountOutputType = {
  documentations: number
}

export type MaintenanceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  documentations?: boolean | MaintenanceCountOutputTypeCountDocumentationsArgs
}

/**
 * MaintenanceCountOutputType without action
 */
export type MaintenanceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MaintenanceCountOutputType
   */
  select?: Prisma.MaintenanceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MaintenanceCountOutputType without action
 */
export type MaintenanceCountOutputTypeCountDocumentationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentationWhereInput
}


export type MaintenanceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  maintenanceID?: boolean
  userID?: boolean
  propertyId?: boolean
  rawRequest?: boolean
  processedRequest?: boolean
  status?: boolean
  schedule?: boolean
  dateIssued?: boolean
  user?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  documentations?: boolean | Prisma.Maintenance$documentationsArgs<ExtArgs>
  _count?: boolean | Prisma.MaintenanceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["maintenance"]>



export type MaintenanceSelectScalar = {
  maintenanceID?: boolean
  userID?: boolean
  propertyId?: boolean
  rawRequest?: boolean
  processedRequest?: boolean
  status?: boolean
  schedule?: boolean
  dateIssued?: boolean
}

export type MaintenanceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"maintenanceID" | "userID" | "propertyId" | "rawRequest" | "processedRequest" | "status" | "schedule" | "dateIssued", ExtArgs["result"]["maintenance"]>
export type MaintenanceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  documentations?: boolean | Prisma.Maintenance$documentationsArgs<ExtArgs>
  _count?: boolean | Prisma.MaintenanceCountOutputTypeDefaultArgs<ExtArgs>
}

export type $MaintenancePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Maintenance"
  objects: {
    user: Prisma.$UsersPayload<ExtArgs>
    property: Prisma.$PropertyPayload<ExtArgs>
    documentations: Prisma.$DocumentationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    maintenanceID: number
    userID: number
    propertyId: number
    rawRequest: string
    processedRequest: string
    status: string
    schedule: Date | null
    dateIssued: Date
  }, ExtArgs["result"]["maintenance"]>
  composites: {}
}

export type MaintenanceGetPayload<S extends boolean | null | undefined | MaintenanceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MaintenancePayload, S>

export type MaintenanceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MaintenanceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MaintenanceCountAggregateInputType | true
  }

export interface MaintenanceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Maintenance'], meta: { name: 'Maintenance' } }
  /**
   * Find zero or one Maintenance that matches the filter.
   * @param {MaintenanceFindUniqueArgs} args - Arguments to find a Maintenance
   * @example
   * // Get one Maintenance
   * const maintenance = await prisma.maintenance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MaintenanceFindUniqueArgs>(args: Prisma.SelectSubset<T, MaintenanceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Maintenance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MaintenanceFindUniqueOrThrowArgs} args - Arguments to find a Maintenance
   * @example
   * // Get one Maintenance
   * const maintenance = await prisma.maintenance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MaintenanceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MaintenanceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Maintenance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceFindFirstArgs} args - Arguments to find a Maintenance
   * @example
   * // Get one Maintenance
   * const maintenance = await prisma.maintenance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MaintenanceFindFirstArgs>(args?: Prisma.SelectSubset<T, MaintenanceFindFirstArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Maintenance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceFindFirstOrThrowArgs} args - Arguments to find a Maintenance
   * @example
   * // Get one Maintenance
   * const maintenance = await prisma.maintenance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MaintenanceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MaintenanceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Maintenances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Maintenances
   * const maintenances = await prisma.maintenance.findMany()
   * 
   * // Get first 10 Maintenances
   * const maintenances = await prisma.maintenance.findMany({ take: 10 })
   * 
   * // Only select the `maintenanceID`
   * const maintenanceWithMaintenanceIDOnly = await prisma.maintenance.findMany({ select: { maintenanceID: true } })
   * 
   */
  findMany<T extends MaintenanceFindManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Maintenance.
   * @param {MaintenanceCreateArgs} args - Arguments to create a Maintenance.
   * @example
   * // Create one Maintenance
   * const Maintenance = await prisma.maintenance.create({
   *   data: {
   *     // ... data to create a Maintenance
   *   }
   * })
   * 
   */
  create<T extends MaintenanceCreateArgs>(args: Prisma.SelectSubset<T, MaintenanceCreateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Maintenances.
   * @param {MaintenanceCreateManyArgs} args - Arguments to create many Maintenances.
   * @example
   * // Create many Maintenances
   * const maintenance = await prisma.maintenance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MaintenanceCreateManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Maintenance.
   * @param {MaintenanceDeleteArgs} args - Arguments to delete one Maintenance.
   * @example
   * // Delete one Maintenance
   * const Maintenance = await prisma.maintenance.delete({
   *   where: {
   *     // ... filter to delete one Maintenance
   *   }
   * })
   * 
   */
  delete<T extends MaintenanceDeleteArgs>(args: Prisma.SelectSubset<T, MaintenanceDeleteArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Maintenance.
   * @param {MaintenanceUpdateArgs} args - Arguments to update one Maintenance.
   * @example
   * // Update one Maintenance
   * const maintenance = await prisma.maintenance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MaintenanceUpdateArgs>(args: Prisma.SelectSubset<T, MaintenanceUpdateArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Maintenances.
   * @param {MaintenanceDeleteManyArgs} args - Arguments to filter Maintenances to delete.
   * @example
   * // Delete a few Maintenances
   * const { count } = await prisma.maintenance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MaintenanceDeleteManyArgs>(args?: Prisma.SelectSubset<T, MaintenanceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Maintenances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Maintenances
   * const maintenance = await prisma.maintenance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MaintenanceUpdateManyArgs>(args: Prisma.SelectSubset<T, MaintenanceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Maintenance.
   * @param {MaintenanceUpsertArgs} args - Arguments to update or create a Maintenance.
   * @example
   * // Update or create a Maintenance
   * const maintenance = await prisma.maintenance.upsert({
   *   create: {
   *     // ... data to create a Maintenance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Maintenance we want to update
   *   }
   * })
   */
  upsert<T extends MaintenanceUpsertArgs>(args: Prisma.SelectSubset<T, MaintenanceUpsertArgs<ExtArgs>>): Prisma.Prisma__MaintenanceClient<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Maintenances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceCountArgs} args - Arguments to filter Maintenances to count.
   * @example
   * // Count the number of Maintenances
   * const count = await prisma.maintenance.count({
   *   where: {
   *     // ... the filter for the Maintenances we want to count
   *   }
   * })
  **/
  count<T extends MaintenanceCountArgs>(
    args?: Prisma.Subset<T, MaintenanceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MaintenanceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Maintenance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MaintenanceAggregateArgs>(args: Prisma.Subset<T, MaintenanceAggregateArgs>): Prisma.PrismaPromise<GetMaintenanceAggregateType<T>>

  /**
   * Group by Maintenance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MaintenanceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MaintenanceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MaintenanceGroupByArgs['orderBy'] }
      : { orderBy?: MaintenanceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MaintenanceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMaintenanceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Maintenance model
 */
readonly fields: MaintenanceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Maintenance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MaintenanceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UsersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsersDefaultArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  property<T extends Prisma.PropertyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PropertyDefaultArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  documentations<T extends Prisma.Maintenance$documentationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Maintenance$documentationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Maintenance model
 */
export interface MaintenanceFieldRefs {
  readonly maintenanceID: Prisma.FieldRef<"Maintenance", 'Int'>
  readonly userID: Prisma.FieldRef<"Maintenance", 'Int'>
  readonly propertyId: Prisma.FieldRef<"Maintenance", 'Int'>
  readonly rawRequest: Prisma.FieldRef<"Maintenance", 'String'>
  readonly processedRequest: Prisma.FieldRef<"Maintenance", 'String'>
  readonly status: Prisma.FieldRef<"Maintenance", 'String'>
  readonly schedule: Prisma.FieldRef<"Maintenance", 'DateTime'>
  readonly dateIssued: Prisma.FieldRef<"Maintenance", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Maintenance findUnique
 */
export type MaintenanceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * Filter, which Maintenance to fetch.
   */
  where: Prisma.MaintenanceWhereUniqueInput
}

/**
 * Maintenance findUniqueOrThrow
 */
export type MaintenanceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * Filter, which Maintenance to fetch.
   */
  where: Prisma.MaintenanceWhereUniqueInput
}

/**
 * Maintenance findFirst
 */
export type MaintenanceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * Filter, which Maintenance to fetch.
   */
  where?: Prisma.MaintenanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Maintenances to fetch.
   */
  orderBy?: Prisma.MaintenanceOrderByWithRelationInput | Prisma.MaintenanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Maintenances.
   */
  cursor?: Prisma.MaintenanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Maintenances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Maintenances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Maintenances.
   */
  distinct?: Prisma.MaintenanceScalarFieldEnum | Prisma.MaintenanceScalarFieldEnum[]
}

/**
 * Maintenance findFirstOrThrow
 */
export type MaintenanceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * Filter, which Maintenance to fetch.
   */
  where?: Prisma.MaintenanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Maintenances to fetch.
   */
  orderBy?: Prisma.MaintenanceOrderByWithRelationInput | Prisma.MaintenanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Maintenances.
   */
  cursor?: Prisma.MaintenanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Maintenances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Maintenances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Maintenances.
   */
  distinct?: Prisma.MaintenanceScalarFieldEnum | Prisma.MaintenanceScalarFieldEnum[]
}

/**
 * Maintenance findMany
 */
export type MaintenanceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * Filter, which Maintenances to fetch.
   */
  where?: Prisma.MaintenanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Maintenances to fetch.
   */
  orderBy?: Prisma.MaintenanceOrderByWithRelationInput | Prisma.MaintenanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Maintenances.
   */
  cursor?: Prisma.MaintenanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Maintenances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Maintenances.
   */
  skip?: number
  distinct?: Prisma.MaintenanceScalarFieldEnum | Prisma.MaintenanceScalarFieldEnum[]
}

/**
 * Maintenance create
 */
export type MaintenanceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * The data needed to create a Maintenance.
   */
  data: Prisma.XOR<Prisma.MaintenanceCreateInput, Prisma.MaintenanceUncheckedCreateInput>
}

/**
 * Maintenance createMany
 */
export type MaintenanceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Maintenances.
   */
  data: Prisma.MaintenanceCreateManyInput | Prisma.MaintenanceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Maintenance update
 */
export type MaintenanceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * The data needed to update a Maintenance.
   */
  data: Prisma.XOR<Prisma.MaintenanceUpdateInput, Prisma.MaintenanceUncheckedUpdateInput>
  /**
   * Choose, which Maintenance to update.
   */
  where: Prisma.MaintenanceWhereUniqueInput
}

/**
 * Maintenance updateMany
 */
export type MaintenanceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Maintenances.
   */
  data: Prisma.XOR<Prisma.MaintenanceUpdateManyMutationInput, Prisma.MaintenanceUncheckedUpdateManyInput>
  /**
   * Filter which Maintenances to update
   */
  where?: Prisma.MaintenanceWhereInput
  /**
   * Limit how many Maintenances to update.
   */
  limit?: number
}

/**
 * Maintenance upsert
 */
export type MaintenanceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * The filter to search for the Maintenance to update in case it exists.
   */
  where: Prisma.MaintenanceWhereUniqueInput
  /**
   * In case the Maintenance found by the `where` argument doesn't exist, create a new Maintenance with this data.
   */
  create: Prisma.XOR<Prisma.MaintenanceCreateInput, Prisma.MaintenanceUncheckedCreateInput>
  /**
   * In case the Maintenance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MaintenanceUpdateInput, Prisma.MaintenanceUncheckedUpdateInput>
}

/**
 * Maintenance delete
 */
export type MaintenanceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  /**
   * Filter which Maintenance to delete.
   */
  where: Prisma.MaintenanceWhereUniqueInput
}

/**
 * Maintenance deleteMany
 */
export type MaintenanceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Maintenances to delete
   */
  where?: Prisma.MaintenanceWhereInput
  /**
   * Limit how many Maintenances to delete.
   */
  limit?: number
}

/**
 * Maintenance.documentations
 */
export type Maintenance$documentationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Documentation
   */
  select?: Prisma.DocumentationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Documentation
   */
  omit?: Prisma.DocumentationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentationInclude<ExtArgs> | null
  where?: Prisma.DocumentationWhereInput
  orderBy?: Prisma.DocumentationOrderByWithRelationInput | Prisma.DocumentationOrderByWithRelationInput[]
  cursor?: Prisma.DocumentationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DocumentationScalarFieldEnum | Prisma.DocumentationScalarFieldEnum[]
}

/**
 * Maintenance without action
 */
export type MaintenanceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
}
