
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Messages` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Messages
 * 
 */
export type MessagesModel = runtime.Types.Result.DefaultSelection<Prisma.$MessagesPayload>

export type AggregateMessages = {
  _count: MessagesCountAggregateOutputType | null
  _avg: MessagesAvgAggregateOutputType | null
  _sum: MessagesSumAggregateOutputType | null
  _min: MessagesMinAggregateOutputType | null
  _max: MessagesMaxAggregateOutputType | null
}

export type MessagesAvgAggregateOutputType = {
  messageID: number | null
  senderID: number | null
  receiverID: number | null
}

export type MessagesSumAggregateOutputType = {
  messageID: number | null
  senderID: number | null
  receiverID: number | null
}

export type MessagesMinAggregateOutputType = {
  messageID: number | null
  senderID: number | null
  receiverID: number | null
  message: string | null
  dateSent: Date | null
}

export type MessagesMaxAggregateOutputType = {
  messageID: number | null
  senderID: number | null
  receiverID: number | null
  message: string | null
  dateSent: Date | null
}

export type MessagesCountAggregateOutputType = {
  messageID: number
  senderID: number
  receiverID: number
  message: number
  dateSent: number
  _all: number
}


export type MessagesAvgAggregateInputType = {
  messageID?: true
  senderID?: true
  receiverID?: true
}

export type MessagesSumAggregateInputType = {
  messageID?: true
  senderID?: true
  receiverID?: true
}

export type MessagesMinAggregateInputType = {
  messageID?: true
  senderID?: true
  receiverID?: true
  message?: true
  dateSent?: true
}

export type MessagesMaxAggregateInputType = {
  messageID?: true
  senderID?: true
  receiverID?: true
  message?: true
  dateSent?: true
}

export type MessagesCountAggregateInputType = {
  messageID?: true
  senderID?: true
  receiverID?: true
  message?: true
  dateSent?: true
  _all?: true
}

export type MessagesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Messages to aggregate.
   */
  where?: Prisma.MessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessagesOrderByWithRelationInput | Prisma.MessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Messages
  **/
  _count?: true | MessagesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MessagesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MessagesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MessagesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MessagesMaxAggregateInputType
}

export type GetMessagesAggregateType<T extends MessagesAggregateArgs> = {
      [P in keyof T & keyof AggregateMessages]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMessages[P]>
    : Prisma.GetScalarType<T[P], AggregateMessages[P]>
}




export type MessagesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessagesWhereInput
  orderBy?: Prisma.MessagesOrderByWithAggregationInput | Prisma.MessagesOrderByWithAggregationInput[]
  by: Prisma.MessagesScalarFieldEnum[] | Prisma.MessagesScalarFieldEnum
  having?: Prisma.MessagesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MessagesCountAggregateInputType | true
  _avg?: MessagesAvgAggregateInputType
  _sum?: MessagesSumAggregateInputType
  _min?: MessagesMinAggregateInputType
  _max?: MessagesMaxAggregateInputType
}

export type MessagesGroupByOutputType = {
  messageID: number
  senderID: number
  receiverID: number
  message: string | null
  dateSent: Date
  _count: MessagesCountAggregateOutputType | null
  _avg: MessagesAvgAggregateOutputType | null
  _sum: MessagesSumAggregateOutputType | null
  _min: MessagesMinAggregateOutputType | null
  _max: MessagesMaxAggregateOutputType | null
}

type GetMessagesGroupByPayload<T extends MessagesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MessagesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MessagesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MessagesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MessagesGroupByOutputType[P]>
      }
    >
  >



export type MessagesWhereInput = {
  AND?: Prisma.MessagesWhereInput | Prisma.MessagesWhereInput[]
  OR?: Prisma.MessagesWhereInput[]
  NOT?: Prisma.MessagesWhereInput | Prisma.MessagesWhereInput[]
  messageID?: Prisma.IntFilter<"Messages"> | number
  senderID?: Prisma.IntFilter<"Messages"> | number
  receiverID?: Prisma.IntFilter<"Messages"> | number
  message?: Prisma.StringNullableFilter<"Messages"> | string | null
  dateSent?: Prisma.DateTimeFilter<"Messages"> | Date | string
  sender?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  receiver?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
}

export type MessagesOrderByWithRelationInput = {
  messageID?: Prisma.SortOrder
  senderID?: Prisma.SortOrder
  receiverID?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  dateSent?: Prisma.SortOrder
  sender?: Prisma.UsersOrderByWithRelationInput
  receiver?: Prisma.UsersOrderByWithRelationInput
  _relevance?: Prisma.MessagesOrderByRelevanceInput
}

export type MessagesWhereUniqueInput = Prisma.AtLeast<{
  messageID?: number
  AND?: Prisma.MessagesWhereInput | Prisma.MessagesWhereInput[]
  OR?: Prisma.MessagesWhereInput[]
  NOT?: Prisma.MessagesWhereInput | Prisma.MessagesWhereInput[]
  senderID?: Prisma.IntFilter<"Messages"> | number
  receiverID?: Prisma.IntFilter<"Messages"> | number
  message?: Prisma.StringNullableFilter<"Messages"> | string | null
  dateSent?: Prisma.DateTimeFilter<"Messages"> | Date | string
  sender?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
  receiver?: Prisma.XOR<Prisma.UsersScalarRelationFilter, Prisma.UsersWhereInput>
}, "messageID">

export type MessagesOrderByWithAggregationInput = {
  messageID?: Prisma.SortOrder
  senderID?: Prisma.SortOrder
  receiverID?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  dateSent?: Prisma.SortOrder
  _count?: Prisma.MessagesCountOrderByAggregateInput
  _avg?: Prisma.MessagesAvgOrderByAggregateInput
  _max?: Prisma.MessagesMaxOrderByAggregateInput
  _min?: Prisma.MessagesMinOrderByAggregateInput
  _sum?: Prisma.MessagesSumOrderByAggregateInput
}

export type MessagesScalarWhereWithAggregatesInput = {
  AND?: Prisma.MessagesScalarWhereWithAggregatesInput | Prisma.MessagesScalarWhereWithAggregatesInput[]
  OR?: Prisma.MessagesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MessagesScalarWhereWithAggregatesInput | Prisma.MessagesScalarWhereWithAggregatesInput[]
  messageID?: Prisma.IntWithAggregatesFilter<"Messages"> | number
  senderID?: Prisma.IntWithAggregatesFilter<"Messages"> | number
  receiverID?: Prisma.IntWithAggregatesFilter<"Messages"> | number
  message?: Prisma.StringNullableWithAggregatesFilter<"Messages"> | string | null
  dateSent?: Prisma.DateTimeWithAggregatesFilter<"Messages"> | Date | string
}

export type MessagesCreateInput = {
  message?: string | null
  dateSent?: Date | string
  sender: Prisma.UsersCreateNestedOneWithoutSentMessagesInput
  receiver: Prisma.UsersCreateNestedOneWithoutReceivedMessagesInput
}

export type MessagesUncheckedCreateInput = {
  messageID?: number
  senderID: number
  receiverID: number
  message?: string | null
  dateSent?: Date | string
}

export type MessagesUpdateInput = {
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sender?: Prisma.UsersUpdateOneRequiredWithoutSentMessagesNestedInput
  receiver?: Prisma.UsersUpdateOneRequiredWithoutReceivedMessagesNestedInput
}

export type MessagesUncheckedUpdateInput = {
  messageID?: Prisma.IntFieldUpdateOperationsInput | number
  senderID?: Prisma.IntFieldUpdateOperationsInput | number
  receiverID?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessagesCreateManyInput = {
  messageID?: number
  senderID: number
  receiverID: number
  message?: string | null
  dateSent?: Date | string
}

export type MessagesUpdateManyMutationInput = {
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessagesUncheckedUpdateManyInput = {
  messageID?: Prisma.IntFieldUpdateOperationsInput | number
  senderID?: Prisma.IntFieldUpdateOperationsInput | number
  receiverID?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessagesListRelationFilter = {
  every?: Prisma.MessagesWhereInput
  some?: Prisma.MessagesWhereInput
  none?: Prisma.MessagesWhereInput
}

export type MessagesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MessagesOrderByRelevanceInput = {
  fields: Prisma.MessagesOrderByRelevanceFieldEnum | Prisma.MessagesOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type MessagesCountOrderByAggregateInput = {
  messageID?: Prisma.SortOrder
  senderID?: Prisma.SortOrder
  receiverID?: Prisma.SortOrder
  message?: Prisma.SortOrder
  dateSent?: Prisma.SortOrder
}

export type MessagesAvgOrderByAggregateInput = {
  messageID?: Prisma.SortOrder
  senderID?: Prisma.SortOrder
  receiverID?: Prisma.SortOrder
}

export type MessagesMaxOrderByAggregateInput = {
  messageID?: Prisma.SortOrder
  senderID?: Prisma.SortOrder
  receiverID?: Prisma.SortOrder
  message?: Prisma.SortOrder
  dateSent?: Prisma.SortOrder
}

export type MessagesMinOrderByAggregateInput = {
  messageID?: Prisma.SortOrder
  senderID?: Prisma.SortOrder
  receiverID?: Prisma.SortOrder
  message?: Prisma.SortOrder
  dateSent?: Prisma.SortOrder
}

export type MessagesSumOrderByAggregateInput = {
  messageID?: Prisma.SortOrder
  senderID?: Prisma.SortOrder
  receiverID?: Prisma.SortOrder
}

export type MessagesCreateNestedManyWithoutSenderInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutSenderInput, Prisma.MessagesUncheckedCreateWithoutSenderInput> | Prisma.MessagesCreateWithoutSenderInput[] | Prisma.MessagesUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutSenderInput | Prisma.MessagesCreateOrConnectWithoutSenderInput[]
  createMany?: Prisma.MessagesCreateManySenderInputEnvelope
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
}

export type MessagesCreateNestedManyWithoutReceiverInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutReceiverInput, Prisma.MessagesUncheckedCreateWithoutReceiverInput> | Prisma.MessagesCreateWithoutReceiverInput[] | Prisma.MessagesUncheckedCreateWithoutReceiverInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutReceiverInput | Prisma.MessagesCreateOrConnectWithoutReceiverInput[]
  createMany?: Prisma.MessagesCreateManyReceiverInputEnvelope
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
}

export type MessagesUncheckedCreateNestedManyWithoutSenderInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutSenderInput, Prisma.MessagesUncheckedCreateWithoutSenderInput> | Prisma.MessagesCreateWithoutSenderInput[] | Prisma.MessagesUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutSenderInput | Prisma.MessagesCreateOrConnectWithoutSenderInput[]
  createMany?: Prisma.MessagesCreateManySenderInputEnvelope
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
}

export type MessagesUncheckedCreateNestedManyWithoutReceiverInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutReceiverInput, Prisma.MessagesUncheckedCreateWithoutReceiverInput> | Prisma.MessagesCreateWithoutReceiverInput[] | Prisma.MessagesUncheckedCreateWithoutReceiverInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutReceiverInput | Prisma.MessagesCreateOrConnectWithoutReceiverInput[]
  createMany?: Prisma.MessagesCreateManyReceiverInputEnvelope
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
}

export type MessagesUpdateManyWithoutSenderNestedInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutSenderInput, Prisma.MessagesUncheckedCreateWithoutSenderInput> | Prisma.MessagesCreateWithoutSenderInput[] | Prisma.MessagesUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutSenderInput | Prisma.MessagesCreateOrConnectWithoutSenderInput[]
  upsert?: Prisma.MessagesUpsertWithWhereUniqueWithoutSenderInput | Prisma.MessagesUpsertWithWhereUniqueWithoutSenderInput[]
  createMany?: Prisma.MessagesCreateManySenderInputEnvelope
  set?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  disconnect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  delete?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  update?: Prisma.MessagesUpdateWithWhereUniqueWithoutSenderInput | Prisma.MessagesUpdateWithWhereUniqueWithoutSenderInput[]
  updateMany?: Prisma.MessagesUpdateManyWithWhereWithoutSenderInput | Prisma.MessagesUpdateManyWithWhereWithoutSenderInput[]
  deleteMany?: Prisma.MessagesScalarWhereInput | Prisma.MessagesScalarWhereInput[]
}

export type MessagesUpdateManyWithoutReceiverNestedInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutReceiverInput, Prisma.MessagesUncheckedCreateWithoutReceiverInput> | Prisma.MessagesCreateWithoutReceiverInput[] | Prisma.MessagesUncheckedCreateWithoutReceiverInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutReceiverInput | Prisma.MessagesCreateOrConnectWithoutReceiverInput[]
  upsert?: Prisma.MessagesUpsertWithWhereUniqueWithoutReceiverInput | Prisma.MessagesUpsertWithWhereUniqueWithoutReceiverInput[]
  createMany?: Prisma.MessagesCreateManyReceiverInputEnvelope
  set?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  disconnect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  delete?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  update?: Prisma.MessagesUpdateWithWhereUniqueWithoutReceiverInput | Prisma.MessagesUpdateWithWhereUniqueWithoutReceiverInput[]
  updateMany?: Prisma.MessagesUpdateManyWithWhereWithoutReceiverInput | Prisma.MessagesUpdateManyWithWhereWithoutReceiverInput[]
  deleteMany?: Prisma.MessagesScalarWhereInput | Prisma.MessagesScalarWhereInput[]
}

export type MessagesUncheckedUpdateManyWithoutSenderNestedInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutSenderInput, Prisma.MessagesUncheckedCreateWithoutSenderInput> | Prisma.MessagesCreateWithoutSenderInput[] | Prisma.MessagesUncheckedCreateWithoutSenderInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutSenderInput | Prisma.MessagesCreateOrConnectWithoutSenderInput[]
  upsert?: Prisma.MessagesUpsertWithWhereUniqueWithoutSenderInput | Prisma.MessagesUpsertWithWhereUniqueWithoutSenderInput[]
  createMany?: Prisma.MessagesCreateManySenderInputEnvelope
  set?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  disconnect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  delete?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  update?: Prisma.MessagesUpdateWithWhereUniqueWithoutSenderInput | Prisma.MessagesUpdateWithWhereUniqueWithoutSenderInput[]
  updateMany?: Prisma.MessagesUpdateManyWithWhereWithoutSenderInput | Prisma.MessagesUpdateManyWithWhereWithoutSenderInput[]
  deleteMany?: Prisma.MessagesScalarWhereInput | Prisma.MessagesScalarWhereInput[]
}

export type MessagesUncheckedUpdateManyWithoutReceiverNestedInput = {
  create?: Prisma.XOR<Prisma.MessagesCreateWithoutReceiverInput, Prisma.MessagesUncheckedCreateWithoutReceiverInput> | Prisma.MessagesCreateWithoutReceiverInput[] | Prisma.MessagesUncheckedCreateWithoutReceiverInput[]
  connectOrCreate?: Prisma.MessagesCreateOrConnectWithoutReceiverInput | Prisma.MessagesCreateOrConnectWithoutReceiverInput[]
  upsert?: Prisma.MessagesUpsertWithWhereUniqueWithoutReceiverInput | Prisma.MessagesUpsertWithWhereUniqueWithoutReceiverInput[]
  createMany?: Prisma.MessagesCreateManyReceiverInputEnvelope
  set?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  disconnect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  delete?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  connect?: Prisma.MessagesWhereUniqueInput | Prisma.MessagesWhereUniqueInput[]
  update?: Prisma.MessagesUpdateWithWhereUniqueWithoutReceiverInput | Prisma.MessagesUpdateWithWhereUniqueWithoutReceiverInput[]
  updateMany?: Prisma.MessagesUpdateManyWithWhereWithoutReceiverInput | Prisma.MessagesUpdateManyWithWhereWithoutReceiverInput[]
  deleteMany?: Prisma.MessagesScalarWhereInput | Prisma.MessagesScalarWhereInput[]
}

export type MessagesCreateWithoutSenderInput = {
  message?: string | null
  dateSent?: Date | string
  receiver: Prisma.UsersCreateNestedOneWithoutReceivedMessagesInput
}

export type MessagesUncheckedCreateWithoutSenderInput = {
  messageID?: number
  receiverID: number
  message?: string | null
  dateSent?: Date | string
}

export type MessagesCreateOrConnectWithoutSenderInput = {
  where: Prisma.MessagesWhereUniqueInput
  create: Prisma.XOR<Prisma.MessagesCreateWithoutSenderInput, Prisma.MessagesUncheckedCreateWithoutSenderInput>
}

export type MessagesCreateManySenderInputEnvelope = {
  data: Prisma.MessagesCreateManySenderInput | Prisma.MessagesCreateManySenderInput[]
  skipDuplicates?: boolean
}

export type MessagesCreateWithoutReceiverInput = {
  message?: string | null
  dateSent?: Date | string
  sender: Prisma.UsersCreateNestedOneWithoutSentMessagesInput
}

export type MessagesUncheckedCreateWithoutReceiverInput = {
  messageID?: number
  senderID: number
  message?: string | null
  dateSent?: Date | string
}

export type MessagesCreateOrConnectWithoutReceiverInput = {
  where: Prisma.MessagesWhereUniqueInput
  create: Prisma.XOR<Prisma.MessagesCreateWithoutReceiverInput, Prisma.MessagesUncheckedCreateWithoutReceiverInput>
}

export type MessagesCreateManyReceiverInputEnvelope = {
  data: Prisma.MessagesCreateManyReceiverInput | Prisma.MessagesCreateManyReceiverInput[]
  skipDuplicates?: boolean
}

export type MessagesUpsertWithWhereUniqueWithoutSenderInput = {
  where: Prisma.MessagesWhereUniqueInput
  update: Prisma.XOR<Prisma.MessagesUpdateWithoutSenderInput, Prisma.MessagesUncheckedUpdateWithoutSenderInput>
  create: Prisma.XOR<Prisma.MessagesCreateWithoutSenderInput, Prisma.MessagesUncheckedCreateWithoutSenderInput>
}

export type MessagesUpdateWithWhereUniqueWithoutSenderInput = {
  where: Prisma.MessagesWhereUniqueInput
  data: Prisma.XOR<Prisma.MessagesUpdateWithoutSenderInput, Prisma.MessagesUncheckedUpdateWithoutSenderInput>
}

export type MessagesUpdateManyWithWhereWithoutSenderInput = {
  where: Prisma.MessagesScalarWhereInput
  data: Prisma.XOR<Prisma.MessagesUpdateManyMutationInput, Prisma.MessagesUncheckedUpdateManyWithoutSenderInput>
}

export type MessagesScalarWhereInput = {
  AND?: Prisma.MessagesScalarWhereInput | Prisma.MessagesScalarWhereInput[]
  OR?: Prisma.MessagesScalarWhereInput[]
  NOT?: Prisma.MessagesScalarWhereInput | Prisma.MessagesScalarWhereInput[]
  messageID?: Prisma.IntFilter<"Messages"> | number
  senderID?: Prisma.IntFilter<"Messages"> | number
  receiverID?: Prisma.IntFilter<"Messages"> | number
  message?: Prisma.StringNullableFilter<"Messages"> | string | null
  dateSent?: Prisma.DateTimeFilter<"Messages"> | Date | string
}

export type MessagesUpsertWithWhereUniqueWithoutReceiverInput = {
  where: Prisma.MessagesWhereUniqueInput
  update: Prisma.XOR<Prisma.MessagesUpdateWithoutReceiverInput, Prisma.MessagesUncheckedUpdateWithoutReceiverInput>
  create: Prisma.XOR<Prisma.MessagesCreateWithoutReceiverInput, Prisma.MessagesUncheckedCreateWithoutReceiverInput>
}

export type MessagesUpdateWithWhereUniqueWithoutReceiverInput = {
  where: Prisma.MessagesWhereUniqueInput
  data: Prisma.XOR<Prisma.MessagesUpdateWithoutReceiverInput, Prisma.MessagesUncheckedUpdateWithoutReceiverInput>
}

export type MessagesUpdateManyWithWhereWithoutReceiverInput = {
  where: Prisma.MessagesScalarWhereInput
  data: Prisma.XOR<Prisma.MessagesUpdateManyMutationInput, Prisma.MessagesUncheckedUpdateManyWithoutReceiverInput>
}

export type MessagesCreateManySenderInput = {
  messageID?: number
  receiverID: number
  message?: string | null
  dateSent?: Date | string
}

export type MessagesCreateManyReceiverInput = {
  messageID?: number
  senderID: number
  message?: string | null
  dateSent?: Date | string
}

export type MessagesUpdateWithoutSenderInput = {
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receiver?: Prisma.UsersUpdateOneRequiredWithoutReceivedMessagesNestedInput
}

export type MessagesUncheckedUpdateWithoutSenderInput = {
  messageID?: Prisma.IntFieldUpdateOperationsInput | number
  receiverID?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessagesUncheckedUpdateManyWithoutSenderInput = {
  messageID?: Prisma.IntFieldUpdateOperationsInput | number
  receiverID?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessagesUpdateWithoutReceiverInput = {
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sender?: Prisma.UsersUpdateOneRequiredWithoutSentMessagesNestedInput
}

export type MessagesUncheckedUpdateWithoutReceiverInput = {
  messageID?: Prisma.IntFieldUpdateOperationsInput | number
  senderID?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MessagesUncheckedUpdateManyWithoutReceiverInput = {
  messageID?: Prisma.IntFieldUpdateOperationsInput | number
  senderID?: Prisma.IntFieldUpdateOperationsInput | number
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dateSent?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MessagesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  messageID?: boolean
  senderID?: boolean
  receiverID?: boolean
  message?: boolean
  dateSent?: boolean
  sender?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  receiver?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
}, ExtArgs["result"]["messages"]>



export type MessagesSelectScalar = {
  messageID?: boolean
  senderID?: boolean
  receiverID?: boolean
  message?: boolean
  dateSent?: boolean
}

export type MessagesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"messageID" | "senderID" | "receiverID" | "message" | "dateSent", ExtArgs["result"]["messages"]>
export type MessagesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sender?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
  receiver?: boolean | Prisma.UsersDefaultArgs<ExtArgs>
}

export type $MessagesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Messages"
  objects: {
    sender: Prisma.$UsersPayload<ExtArgs>
    receiver: Prisma.$UsersPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    messageID: number
    senderID: number
    receiverID: number
    message: string | null
    dateSent: Date
  }, ExtArgs["result"]["messages"]>
  composites: {}
}

export type MessagesGetPayload<S extends boolean | null | undefined | MessagesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MessagesPayload, S>

export type MessagesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MessagesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MessagesCountAggregateInputType | true
  }

export interface MessagesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Messages'], meta: { name: 'Messages' } }
  /**
   * Find zero or one Messages that matches the filter.
   * @param {MessagesFindUniqueArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MessagesFindUniqueArgs>(args: Prisma.SelectSubset<T, MessagesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Messages that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MessagesFindUniqueOrThrowArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MessagesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MessagesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Messages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesFindFirstArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MessagesFindFirstArgs>(args?: Prisma.SelectSubset<T, MessagesFindFirstArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Messages that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesFindFirstOrThrowArgs} args - Arguments to find a Messages
   * @example
   * // Get one Messages
   * const messages = await prisma.messages.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MessagesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MessagesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Messages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Messages
   * const messages = await prisma.messages.findMany()
   * 
   * // Get first 10 Messages
   * const messages = await prisma.messages.findMany({ take: 10 })
   * 
   * // Only select the `messageID`
   * const messagesWithMessageIDOnly = await prisma.messages.findMany({ select: { messageID: true } })
   * 
   */
  findMany<T extends MessagesFindManyArgs>(args?: Prisma.SelectSubset<T, MessagesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Messages.
   * @param {MessagesCreateArgs} args - Arguments to create a Messages.
   * @example
   * // Create one Messages
   * const Messages = await prisma.messages.create({
   *   data: {
   *     // ... data to create a Messages
   *   }
   * })
   * 
   */
  create<T extends MessagesCreateArgs>(args: Prisma.SelectSubset<T, MessagesCreateArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Messages.
   * @param {MessagesCreateManyArgs} args - Arguments to create many Messages.
   * @example
   * // Create many Messages
   * const messages = await prisma.messages.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MessagesCreateManyArgs>(args?: Prisma.SelectSubset<T, MessagesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Messages.
   * @param {MessagesDeleteArgs} args - Arguments to delete one Messages.
   * @example
   * // Delete one Messages
   * const Messages = await prisma.messages.delete({
   *   where: {
   *     // ... filter to delete one Messages
   *   }
   * })
   * 
   */
  delete<T extends MessagesDeleteArgs>(args: Prisma.SelectSubset<T, MessagesDeleteArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Messages.
   * @param {MessagesUpdateArgs} args - Arguments to update one Messages.
   * @example
   * // Update one Messages
   * const messages = await prisma.messages.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MessagesUpdateArgs>(args: Prisma.SelectSubset<T, MessagesUpdateArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Messages.
   * @param {MessagesDeleteManyArgs} args - Arguments to filter Messages to delete.
   * @example
   * // Delete a few Messages
   * const { count } = await prisma.messages.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MessagesDeleteManyArgs>(args?: Prisma.SelectSubset<T, MessagesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Messages
   * const messages = await prisma.messages.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MessagesUpdateManyArgs>(args: Prisma.SelectSubset<T, MessagesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Messages.
   * @param {MessagesUpsertArgs} args - Arguments to update or create a Messages.
   * @example
   * // Update or create a Messages
   * const messages = await prisma.messages.upsert({
   *   create: {
   *     // ... data to create a Messages
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Messages we want to update
   *   }
   * })
   */
  upsert<T extends MessagesUpsertArgs>(args: Prisma.SelectSubset<T, MessagesUpsertArgs<ExtArgs>>): Prisma.Prisma__MessagesClient<runtime.Types.Result.GetResult<Prisma.$MessagesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesCountArgs} args - Arguments to filter Messages to count.
   * @example
   * // Count the number of Messages
   * const count = await prisma.messages.count({
   *   where: {
   *     // ... the filter for the Messages we want to count
   *   }
   * })
  **/
  count<T extends MessagesCountArgs>(
    args?: Prisma.Subset<T, MessagesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MessagesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MessagesAggregateArgs>(args: Prisma.Subset<T, MessagesAggregateArgs>): Prisma.PrismaPromise<GetMessagesAggregateType<T>>

  /**
   * Group by Messages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MessagesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MessagesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MessagesGroupByArgs['orderBy'] }
      : { orderBy?: MessagesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MessagesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMessagesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Messages model
 */
readonly fields: MessagesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Messages.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MessagesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sender<T extends Prisma.UsersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsersDefaultArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  receiver<T extends Prisma.UsersDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsersDefaultArgs<ExtArgs>>): Prisma.Prisma__UsersClient<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Messages model
 */
export interface MessagesFieldRefs {
  readonly messageID: Prisma.FieldRef<"Messages", 'Int'>
  readonly senderID: Prisma.FieldRef<"Messages", 'Int'>
  readonly receiverID: Prisma.FieldRef<"Messages", 'Int'>
  readonly message: Prisma.FieldRef<"Messages", 'String'>
  readonly dateSent: Prisma.FieldRef<"Messages", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Messages findUnique
 */
export type MessagesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * Filter, which Messages to fetch.
   */
  where: Prisma.MessagesWhereUniqueInput
}

/**
 * Messages findUniqueOrThrow
 */
export type MessagesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * Filter, which Messages to fetch.
   */
  where: Prisma.MessagesWhereUniqueInput
}

/**
 * Messages findFirst
 */
export type MessagesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * Filter, which Messages to fetch.
   */
  where?: Prisma.MessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessagesOrderByWithRelationInput | Prisma.MessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Messages.
   */
  cursor?: Prisma.MessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessagesScalarFieldEnum | Prisma.MessagesScalarFieldEnum[]
}

/**
 * Messages findFirstOrThrow
 */
export type MessagesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * Filter, which Messages to fetch.
   */
  where?: Prisma.MessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessagesOrderByWithRelationInput | Prisma.MessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Messages.
   */
  cursor?: Prisma.MessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Messages.
   */
  distinct?: Prisma.MessagesScalarFieldEnum | Prisma.MessagesScalarFieldEnum[]
}

/**
 * Messages findMany
 */
export type MessagesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * Filter, which Messages to fetch.
   */
  where?: Prisma.MessagesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Messages to fetch.
   */
  orderBy?: Prisma.MessagesOrderByWithRelationInput | Prisma.MessagesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Messages.
   */
  cursor?: Prisma.MessagesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Messages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Messages.
   */
  skip?: number
  distinct?: Prisma.MessagesScalarFieldEnum | Prisma.MessagesScalarFieldEnum[]
}

/**
 * Messages create
 */
export type MessagesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * The data needed to create a Messages.
   */
  data: Prisma.XOR<Prisma.MessagesCreateInput, Prisma.MessagesUncheckedCreateInput>
}

/**
 * Messages createMany
 */
export type MessagesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Messages.
   */
  data: Prisma.MessagesCreateManyInput | Prisma.MessagesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Messages update
 */
export type MessagesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * The data needed to update a Messages.
   */
  data: Prisma.XOR<Prisma.MessagesUpdateInput, Prisma.MessagesUncheckedUpdateInput>
  /**
   * Choose, which Messages to update.
   */
  where: Prisma.MessagesWhereUniqueInput
}

/**
 * Messages updateMany
 */
export type MessagesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Messages.
   */
  data: Prisma.XOR<Prisma.MessagesUpdateManyMutationInput, Prisma.MessagesUncheckedUpdateManyInput>
  /**
   * Filter which Messages to update
   */
  where?: Prisma.MessagesWhereInput
  /**
   * Limit how many Messages to update.
   */
  limit?: number
}

/**
 * Messages upsert
 */
export type MessagesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * The filter to search for the Messages to update in case it exists.
   */
  where: Prisma.MessagesWhereUniqueInput
  /**
   * In case the Messages found by the `where` argument doesn't exist, create a new Messages with this data.
   */
  create: Prisma.XOR<Prisma.MessagesCreateInput, Prisma.MessagesUncheckedCreateInput>
  /**
   * In case the Messages was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MessagesUpdateInput, Prisma.MessagesUncheckedUpdateInput>
}

/**
 * Messages delete
 */
export type MessagesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
  /**
   * Filter which Messages to delete.
   */
  where: Prisma.MessagesWhereUniqueInput
}

/**
 * Messages deleteMany
 */
export type MessagesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Messages to delete
   */
  where?: Prisma.MessagesWhereInput
  /**
   * Limit how many Messages to delete.
   */
  limit?: number
}

/**
 * Messages without action
 */
export type MessagesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Messages
   */
  select?: Prisma.MessagesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Messages
   */
  omit?: Prisma.MessagesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessagesInclude<ExtArgs> | null
}
