
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Property` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Property
 * 
 */
export type PropertyModel = runtime.Types.Result.DefaultSelection<Prisma.$PropertyPayload>

export type AggregateProperty = {
  _count: PropertyCountAggregateOutputType | null
  _avg: PropertyAvgAggregateOutputType | null
  _sum: PropertySumAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

export type PropertyAvgAggregateOutputType = {
  propertyId: number | null
  rent: number | null
  area: number | null
  yearBuilt: number | null
}

export type PropertySumAggregateOutputType = {
  propertyId: number | null
  rent: number | null
  area: number | null
  yearBuilt: number | null
}

export type PropertyMinAggregateOutputType = {
  propertyId: number | null
  name: string | null
  rent: number | null
  area: number | null
  yearBuilt: number | null
  renovated: boolean | null
  address: string | null
  description: string | null
  createdAt: Date | null
}

export type PropertyMaxAggregateOutputType = {
  propertyId: number | null
  name: string | null
  rent: number | null
  area: number | null
  yearBuilt: number | null
  renovated: boolean | null
  address: string | null
  description: string | null
  createdAt: Date | null
}

export type PropertyCountAggregateOutputType = {
  propertyId: number
  name: number
  rent: number
  area: number
  yearBuilt: number
  renovated: number
  address: number
  description: number
  createdAt: number
  _all: number
}


export type PropertyAvgAggregateInputType = {
  propertyId?: true
  rent?: true
  area?: true
  yearBuilt?: true
}

export type PropertySumAggregateInputType = {
  propertyId?: true
  rent?: true
  area?: true
  yearBuilt?: true
}

export type PropertyMinAggregateInputType = {
  propertyId?: true
  name?: true
  rent?: true
  area?: true
  yearBuilt?: true
  renovated?: true
  address?: true
  description?: true
  createdAt?: true
}

export type PropertyMaxAggregateInputType = {
  propertyId?: true
  name?: true
  rent?: true
  area?: true
  yearBuilt?: true
  renovated?: true
  address?: true
  description?: true
  createdAt?: true
}

export type PropertyCountAggregateInputType = {
  propertyId?: true
  name?: true
  rent?: true
  area?: true
  yearBuilt?: true
  renovated?: true
  address?: true
  description?: true
  createdAt?: true
  _all?: true
}

export type PropertyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Property to aggregate.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Properties
  **/
  _count?: true | PropertyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PropertyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PropertySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PropertyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PropertyMaxAggregateInputType
}

export type GetPropertyAggregateType<T extends PropertyAggregateArgs> = {
      [P in keyof T & keyof AggregateProperty]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProperty[P]>
    : Prisma.GetScalarType<T[P], AggregateProperty[P]>
}




export type PropertyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyWhereInput
  orderBy?: Prisma.PropertyOrderByWithAggregationInput | Prisma.PropertyOrderByWithAggregationInput[]
  by: Prisma.PropertyScalarFieldEnum[] | Prisma.PropertyScalarFieldEnum
  having?: Prisma.PropertyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PropertyCountAggregateInputType | true
  _avg?: PropertyAvgAggregateInputType
  _sum?: PropertySumAggregateInputType
  _min?: PropertyMinAggregateInputType
  _max?: PropertyMaxAggregateInputType
}

export type PropertyGroupByOutputType = {
  propertyId: number
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt: Date
  _count: PropertyCountAggregateOutputType | null
  _avg: PropertyAvgAggregateOutputType | null
  _sum: PropertySumAggregateOutputType | null
  _min: PropertyMinAggregateOutputType | null
  _max: PropertyMaxAggregateOutputType | null
}

type GetPropertyGroupByPayload<T extends PropertyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PropertyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PropertyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PropertyGroupByOutputType[P]>
      }
    >
  >



export type PropertyWhereInput = {
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  propertyId?: Prisma.IntFilter<"Property"> | number
  name?: Prisma.StringFilter<"Property"> | string
  rent?: Prisma.FloatFilter<"Property"> | number
  area?: Prisma.FloatFilter<"Property"> | number
  yearBuilt?: Prisma.IntFilter<"Property"> | number
  renovated?: Prisma.BoolFilter<"Property"> | boolean
  address?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringFilter<"Property"> | string
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  billings?: Prisma.BillingListRelationFilter
  maintenances?: Prisma.MaintenanceListRelationFilter
  feedbacks?: Prisma.FeedbackListRelationFilter
  users?: Prisma.UsersListRelationFilter
}

export type PropertyOrderByWithRelationInput = {
  propertyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  area?: Prisma.SortOrder
  yearBuilt?: Prisma.SortOrder
  renovated?: Prisma.SortOrder
  address?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  billings?: Prisma.BillingOrderByRelationAggregateInput
  maintenances?: Prisma.MaintenanceOrderByRelationAggregateInput
  feedbacks?: Prisma.FeedbackOrderByRelationAggregateInput
  users?: Prisma.UsersOrderByRelationAggregateInput
  _relevance?: Prisma.PropertyOrderByRelevanceInput
}

export type PropertyWhereUniqueInput = Prisma.AtLeast<{
  propertyId?: number
  AND?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  OR?: Prisma.PropertyWhereInput[]
  NOT?: Prisma.PropertyWhereInput | Prisma.PropertyWhereInput[]
  name?: Prisma.StringFilter<"Property"> | string
  rent?: Prisma.FloatFilter<"Property"> | number
  area?: Prisma.FloatFilter<"Property"> | number
  yearBuilt?: Prisma.IntFilter<"Property"> | number
  renovated?: Prisma.BoolFilter<"Property"> | boolean
  address?: Prisma.StringFilter<"Property"> | string
  description?: Prisma.StringFilter<"Property"> | string
  createdAt?: Prisma.DateTimeFilter<"Property"> | Date | string
  billings?: Prisma.BillingListRelationFilter
  maintenances?: Prisma.MaintenanceListRelationFilter
  feedbacks?: Prisma.FeedbackListRelationFilter
  users?: Prisma.UsersListRelationFilter
}, "propertyId">

export type PropertyOrderByWithAggregationInput = {
  propertyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  area?: Prisma.SortOrder
  yearBuilt?: Prisma.SortOrder
  renovated?: Prisma.SortOrder
  address?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.PropertyCountOrderByAggregateInput
  _avg?: Prisma.PropertyAvgOrderByAggregateInput
  _max?: Prisma.PropertyMaxOrderByAggregateInput
  _min?: Prisma.PropertyMinOrderByAggregateInput
  _sum?: Prisma.PropertySumOrderByAggregateInput
}

export type PropertyScalarWhereWithAggregatesInput = {
  AND?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  OR?: Prisma.PropertyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PropertyScalarWhereWithAggregatesInput | Prisma.PropertyScalarWhereWithAggregatesInput[]
  propertyId?: Prisma.IntWithAggregatesFilter<"Property"> | number
  name?: Prisma.StringWithAggregatesFilter<"Property"> | string
  rent?: Prisma.FloatWithAggregatesFilter<"Property"> | number
  area?: Prisma.FloatWithAggregatesFilter<"Property"> | number
  yearBuilt?: Prisma.IntWithAggregatesFilter<"Property"> | number
  renovated?: Prisma.BoolWithAggregatesFilter<"Property"> | boolean
  address?: Prisma.StringWithAggregatesFilter<"Property"> | string
  description?: Prisma.StringWithAggregatesFilter<"Property"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Property"> | Date | string
}

export type PropertyCreateInput = {
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingCreateNestedManyWithoutPropertyInput
  maintenances?: Prisma.MaintenanceCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateInput = {
  propertyId?: number
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingUncheckedCreateNestedManyWithoutPropertyInput
  maintenances?: Prisma.MaintenanceUncheckedCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackUncheckedCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUpdateManyWithoutPropertyNestedInput
  maintenances?: Prisma.MaintenanceUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateInput = {
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUncheckedUpdateManyWithoutPropertyNestedInput
  maintenances?: Prisma.MaintenanceUncheckedUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUncheckedUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateManyInput = {
  propertyId?: number
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
}

export type PropertyUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyUncheckedUpdateManyInput = {
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PropertyNullableScalarRelationFilter = {
  is?: Prisma.PropertyWhereInput | null
  isNot?: Prisma.PropertyWhereInput | null
}

export type PropertyOrderByRelevanceInput = {
  fields: Prisma.PropertyOrderByRelevanceFieldEnum | Prisma.PropertyOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PropertyCountOrderByAggregateInput = {
  propertyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  area?: Prisma.SortOrder
  yearBuilt?: Prisma.SortOrder
  renovated?: Prisma.SortOrder
  address?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PropertyAvgOrderByAggregateInput = {
  propertyId?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  area?: Prisma.SortOrder
  yearBuilt?: Prisma.SortOrder
}

export type PropertyMaxOrderByAggregateInput = {
  propertyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  area?: Prisma.SortOrder
  yearBuilt?: Prisma.SortOrder
  renovated?: Prisma.SortOrder
  address?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PropertyMinOrderByAggregateInput = {
  propertyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  area?: Prisma.SortOrder
  yearBuilt?: Prisma.SortOrder
  renovated?: Prisma.SortOrder
  address?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type PropertySumOrderByAggregateInput = {
  propertyId?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  area?: Prisma.SortOrder
  yearBuilt?: Prisma.SortOrder
}

export type PropertyScalarRelationFilter = {
  is?: Prisma.PropertyWhereInput
  isNot?: Prisma.PropertyWhereInput
}

export type PropertyCreateNestedOneWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutUsersInput, Prisma.PropertyUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutUsersInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutUsersInput, Prisma.PropertyUncheckedCreateWithoutUsersInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutUsersInput
  upsert?: Prisma.PropertyUpsertWithoutUsersInput
  disconnect?: Prisma.PropertyWhereInput | boolean
  delete?: Prisma.PropertyWhereInput | boolean
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutUsersInput, Prisma.PropertyUpdateWithoutUsersInput>, Prisma.PropertyUncheckedUpdateWithoutUsersInput>
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type PropertyCreateNestedOneWithoutBillingsInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutBillingsInput, Prisma.PropertyUncheckedCreateWithoutBillingsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutBillingsInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutBillingsNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutBillingsInput, Prisma.PropertyUncheckedCreateWithoutBillingsInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutBillingsInput
  upsert?: Prisma.PropertyUpsertWithoutBillingsInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutBillingsInput, Prisma.PropertyUpdateWithoutBillingsInput>, Prisma.PropertyUncheckedUpdateWithoutBillingsInput>
}

export type PropertyCreateNestedOneWithoutMaintenancesInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutMaintenancesInput, Prisma.PropertyUncheckedCreateWithoutMaintenancesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutMaintenancesInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutMaintenancesNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutMaintenancesInput, Prisma.PropertyUncheckedCreateWithoutMaintenancesInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutMaintenancesInput
  upsert?: Prisma.PropertyUpsertWithoutMaintenancesInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutMaintenancesInput, Prisma.PropertyUpdateWithoutMaintenancesInput>, Prisma.PropertyUncheckedUpdateWithoutMaintenancesInput>
}

export type PropertyCreateNestedOneWithoutFeedbacksInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutFeedbacksInput, Prisma.PropertyUncheckedCreateWithoutFeedbacksInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutFeedbacksInput
  connect?: Prisma.PropertyWhereUniqueInput
}

export type PropertyUpdateOneRequiredWithoutFeedbacksNestedInput = {
  create?: Prisma.XOR<Prisma.PropertyCreateWithoutFeedbacksInput, Prisma.PropertyUncheckedCreateWithoutFeedbacksInput>
  connectOrCreate?: Prisma.PropertyCreateOrConnectWithoutFeedbacksInput
  upsert?: Prisma.PropertyUpsertWithoutFeedbacksInput
  connect?: Prisma.PropertyWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PropertyUpdateToOneWithWhereWithoutFeedbacksInput, Prisma.PropertyUpdateWithoutFeedbacksInput>, Prisma.PropertyUncheckedUpdateWithoutFeedbacksInput>
}

export type PropertyCreateWithoutUsersInput = {
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingCreateNestedManyWithoutPropertyInput
  maintenances?: Prisma.MaintenanceCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutUsersInput = {
  propertyId?: number
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingUncheckedCreateNestedManyWithoutPropertyInput
  maintenances?: Prisma.MaintenanceUncheckedCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutUsersInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutUsersInput, Prisma.PropertyUncheckedCreateWithoutUsersInput>
}

export type PropertyUpsertWithoutUsersInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutUsersInput, Prisma.PropertyUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutUsersInput, Prisma.PropertyUncheckedCreateWithoutUsersInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutUsersInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutUsersInput, Prisma.PropertyUncheckedUpdateWithoutUsersInput>
}

export type PropertyUpdateWithoutUsersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUpdateManyWithoutPropertyNestedInput
  maintenances?: Prisma.MaintenanceUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutUsersInput = {
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUncheckedUpdateManyWithoutPropertyNestedInput
  maintenances?: Prisma.MaintenanceUncheckedUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutBillingsInput = {
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  maintenances?: Prisma.MaintenanceCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutBillingsInput = {
  propertyId?: number
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  maintenances?: Prisma.MaintenanceUncheckedCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackUncheckedCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutBillingsInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutBillingsInput, Prisma.PropertyUncheckedCreateWithoutBillingsInput>
}

export type PropertyUpsertWithoutBillingsInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutBillingsInput, Prisma.PropertyUncheckedUpdateWithoutBillingsInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutBillingsInput, Prisma.PropertyUncheckedCreateWithoutBillingsInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutBillingsInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutBillingsInput, Prisma.PropertyUncheckedUpdateWithoutBillingsInput>
}

export type PropertyUpdateWithoutBillingsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenances?: Prisma.MaintenanceUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutBillingsInput = {
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maintenances?: Prisma.MaintenanceUncheckedUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUncheckedUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutMaintenancesInput = {
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutMaintenancesInput = {
  propertyId?: number
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingUncheckedCreateNestedManyWithoutPropertyInput
  feedbacks?: Prisma.FeedbackUncheckedCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutMaintenancesInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutMaintenancesInput, Prisma.PropertyUncheckedCreateWithoutMaintenancesInput>
}

export type PropertyUpsertWithoutMaintenancesInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutMaintenancesInput, Prisma.PropertyUncheckedUpdateWithoutMaintenancesInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutMaintenancesInput, Prisma.PropertyUncheckedCreateWithoutMaintenancesInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutMaintenancesInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutMaintenancesInput, Prisma.PropertyUncheckedUpdateWithoutMaintenancesInput>
}

export type PropertyUpdateWithoutMaintenancesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutMaintenancesInput = {
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUncheckedUpdateManyWithoutPropertyNestedInput
  feedbacks?: Prisma.FeedbackUncheckedUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUncheckedUpdateManyWithoutPropertyNestedInput
}

export type PropertyCreateWithoutFeedbacksInput = {
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingCreateNestedManyWithoutPropertyInput
  maintenances?: Prisma.MaintenanceCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersCreateNestedManyWithoutPropertyInput
}

export type PropertyUncheckedCreateWithoutFeedbacksInput = {
  propertyId?: number
  name: string
  rent: number
  area: number
  yearBuilt: number
  renovated: boolean
  address: string
  description: string
  createdAt?: Date | string
  billings?: Prisma.BillingUncheckedCreateNestedManyWithoutPropertyInput
  maintenances?: Prisma.MaintenanceUncheckedCreateNestedManyWithoutPropertyInput
  users?: Prisma.UsersUncheckedCreateNestedManyWithoutPropertyInput
}

export type PropertyCreateOrConnectWithoutFeedbacksInput = {
  where: Prisma.PropertyWhereUniqueInput
  create: Prisma.XOR<Prisma.PropertyCreateWithoutFeedbacksInput, Prisma.PropertyUncheckedCreateWithoutFeedbacksInput>
}

export type PropertyUpsertWithoutFeedbacksInput = {
  update: Prisma.XOR<Prisma.PropertyUpdateWithoutFeedbacksInput, Prisma.PropertyUncheckedUpdateWithoutFeedbacksInput>
  create: Prisma.XOR<Prisma.PropertyCreateWithoutFeedbacksInput, Prisma.PropertyUncheckedCreateWithoutFeedbacksInput>
  where?: Prisma.PropertyWhereInput
}

export type PropertyUpdateToOneWithWhereWithoutFeedbacksInput = {
  where?: Prisma.PropertyWhereInput
  data: Prisma.XOR<Prisma.PropertyUpdateWithoutFeedbacksInput, Prisma.PropertyUncheckedUpdateWithoutFeedbacksInput>
}

export type PropertyUpdateWithoutFeedbacksInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUpdateManyWithoutPropertyNestedInput
  maintenances?: Prisma.MaintenanceUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUpdateManyWithoutPropertyNestedInput
}

export type PropertyUncheckedUpdateWithoutFeedbacksInput = {
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  area?: Prisma.FloatFieldUpdateOperationsInput | number
  yearBuilt?: Prisma.IntFieldUpdateOperationsInput | number
  renovated?: Prisma.BoolFieldUpdateOperationsInput | boolean
  address?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  billings?: Prisma.BillingUncheckedUpdateManyWithoutPropertyNestedInput
  maintenances?: Prisma.MaintenanceUncheckedUpdateManyWithoutPropertyNestedInput
  users?: Prisma.UsersUncheckedUpdateManyWithoutPropertyNestedInput
}


/**
 * Count Type PropertyCountOutputType
 */

export type PropertyCountOutputType = {
  billings: number
  maintenances: number
  feedbacks: number
  users: number
}

export type PropertyCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  billings?: boolean | PropertyCountOutputTypeCountBillingsArgs
  maintenances?: boolean | PropertyCountOutputTypeCountMaintenancesArgs
  feedbacks?: boolean | PropertyCountOutputTypeCountFeedbacksArgs
  users?: boolean | PropertyCountOutputTypeCountUsersArgs
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PropertyCountOutputType
   */
  select?: Prisma.PropertyCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountBillingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BillingWhereInput
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountMaintenancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MaintenanceWhereInput
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountFeedbacksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeedbackWhereInput
}

/**
 * PropertyCountOutputType without action
 */
export type PropertyCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsersWhereInput
}


export type PropertySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  propertyId?: boolean
  name?: boolean
  rent?: boolean
  area?: boolean
  yearBuilt?: boolean
  renovated?: boolean
  address?: boolean
  description?: boolean
  createdAt?: boolean
  billings?: boolean | Prisma.Property$billingsArgs<ExtArgs>
  maintenances?: boolean | Prisma.Property$maintenancesArgs<ExtArgs>
  feedbacks?: boolean | Prisma.Property$feedbacksArgs<ExtArgs>
  users?: boolean | Prisma.Property$usersArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property"]>



export type PropertySelectScalar = {
  propertyId?: boolean
  name?: boolean
  rent?: boolean
  area?: boolean
  yearBuilt?: boolean
  renovated?: boolean
  address?: boolean
  description?: boolean
  createdAt?: boolean
}

export type PropertyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"propertyId" | "name" | "rent" | "area" | "yearBuilt" | "renovated" | "address" | "description" | "createdAt", ExtArgs["result"]["property"]>
export type PropertyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  billings?: boolean | Prisma.Property$billingsArgs<ExtArgs>
  maintenances?: boolean | Prisma.Property$maintenancesArgs<ExtArgs>
  feedbacks?: boolean | Prisma.Property$feedbacksArgs<ExtArgs>
  users?: boolean | Prisma.Property$usersArgs<ExtArgs>
  _count?: boolean | Prisma.PropertyCountOutputTypeDefaultArgs<ExtArgs>
}

export type $PropertyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Property"
  objects: {
    billings: Prisma.$BillingPayload<ExtArgs>[]
    maintenances: Prisma.$MaintenancePayload<ExtArgs>[]
    feedbacks: Prisma.$FeedbackPayload<ExtArgs>[]
    users: Prisma.$UsersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    propertyId: number
    name: string
    rent: number
    area: number
    yearBuilt: number
    renovated: boolean
    address: string
    description: string
    createdAt: Date
  }, ExtArgs["result"]["property"]>
  composites: {}
}

export type PropertyGetPayload<S extends boolean | null | undefined | PropertyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PropertyPayload, S>

export type PropertyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PropertyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PropertyCountAggregateInputType | true
  }

export interface PropertyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Property'], meta: { name: 'Property' } }
  /**
   * Find zero or one Property that matches the filter.
   * @param {PropertyFindUniqueArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PropertyFindUniqueArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Property that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PropertyFindUniqueOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PropertyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PropertyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PropertyFindFirstArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindFirstOrThrowArgs} args - Arguments to find a Property
   * @example
   * // Get one Property
   * const property = await prisma.property.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PropertyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PropertyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Properties that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Properties
   * const properties = await prisma.property.findMany()
   * 
   * // Get first 10 Properties
   * const properties = await prisma.property.findMany({ take: 10 })
   * 
   * // Only select the `propertyId`
   * const propertyWithPropertyIdOnly = await prisma.property.findMany({ select: { propertyId: true } })
   * 
   */
  findMany<T extends PropertyFindManyArgs>(args?: Prisma.SelectSubset<T, PropertyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Property.
   * @param {PropertyCreateArgs} args - Arguments to create a Property.
   * @example
   * // Create one Property
   * const Property = await prisma.property.create({
   *   data: {
   *     // ... data to create a Property
   *   }
   * })
   * 
   */
  create<T extends PropertyCreateArgs>(args: Prisma.SelectSubset<T, PropertyCreateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Properties.
   * @param {PropertyCreateManyArgs} args - Arguments to create many Properties.
   * @example
   * // Create many Properties
   * const property = await prisma.property.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PropertyCreateManyArgs>(args?: Prisma.SelectSubset<T, PropertyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Property.
   * @param {PropertyDeleteArgs} args - Arguments to delete one Property.
   * @example
   * // Delete one Property
   * const Property = await prisma.property.delete({
   *   where: {
   *     // ... filter to delete one Property
   *   }
   * })
   * 
   */
  delete<T extends PropertyDeleteArgs>(args: Prisma.SelectSubset<T, PropertyDeleteArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Property.
   * @param {PropertyUpdateArgs} args - Arguments to update one Property.
   * @example
   * // Update one Property
   * const property = await prisma.property.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PropertyUpdateArgs>(args: Prisma.SelectSubset<T, PropertyUpdateArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Properties.
   * @param {PropertyDeleteManyArgs} args - Arguments to filter Properties to delete.
   * @example
   * // Delete a few Properties
   * const { count } = await prisma.property.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PropertyDeleteManyArgs>(args?: Prisma.SelectSubset<T, PropertyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Properties
   * const property = await prisma.property.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PropertyUpdateManyArgs>(args: Prisma.SelectSubset<T, PropertyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Property.
   * @param {PropertyUpsertArgs} args - Arguments to update or create a Property.
   * @example
   * // Update or create a Property
   * const property = await prisma.property.upsert({
   *   create: {
   *     // ... data to create a Property
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Property we want to update
   *   }
   * })
   */
  upsert<T extends PropertyUpsertArgs>(args: Prisma.SelectSubset<T, PropertyUpsertArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Properties.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyCountArgs} args - Arguments to filter Properties to count.
   * @example
   * // Count the number of Properties
   * const count = await prisma.property.count({
   *   where: {
   *     // ... the filter for the Properties we want to count
   *   }
   * })
  **/
  count<T extends PropertyCountArgs>(
    args?: Prisma.Subset<T, PropertyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PropertyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PropertyAggregateArgs>(args: Prisma.Subset<T, PropertyAggregateArgs>): Prisma.PrismaPromise<GetPropertyAggregateType<T>>

  /**
   * Group by Property.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PropertyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PropertyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PropertyGroupByArgs['orderBy'] }
      : { orderBy?: PropertyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PropertyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPropertyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Property model
 */
readonly fields: PropertyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Property.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PropertyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  billings<T extends Prisma.Property$billingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$billingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BillingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  maintenances<T extends Prisma.Property$maintenancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$maintenancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MaintenancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  feedbacks<T extends Prisma.Property$feedbacksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$feedbacksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  users<T extends Prisma.Property$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Property$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Property model
 */
export interface PropertyFieldRefs {
  readonly propertyId: Prisma.FieldRef<"Property", 'Int'>
  readonly name: Prisma.FieldRef<"Property", 'String'>
  readonly rent: Prisma.FieldRef<"Property", 'Float'>
  readonly area: Prisma.FieldRef<"Property", 'Float'>
  readonly yearBuilt: Prisma.FieldRef<"Property", 'Int'>
  readonly renovated: Prisma.FieldRef<"Property", 'Boolean'>
  readonly address: Prisma.FieldRef<"Property", 'String'>
  readonly description: Prisma.FieldRef<"Property", 'String'>
  readonly createdAt: Prisma.FieldRef<"Property", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Property findUnique
 */
export type PropertyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findUniqueOrThrow
 */
export type PropertyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property findFirst
 */
export type PropertyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findFirstOrThrow
 */
export type PropertyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Property to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Properties.
   */
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property findMany
 */
export type PropertyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter, which Properties to fetch.
   */
  where?: Prisma.PropertyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Properties to fetch.
   */
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Properties.
   */
  cursor?: Prisma.PropertyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Properties from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Properties.
   */
  skip?: number
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Property create
 */
export type PropertyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to create a Property.
   */
  data: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
}

/**
 * Property createMany
 */
export type PropertyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Properties.
   */
  data: Prisma.PropertyCreateManyInput | Prisma.PropertyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Property update
 */
export type PropertyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The data needed to update a Property.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
  /**
   * Choose, which Property to update.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property updateMany
 */
export type PropertyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Properties.
   */
  data: Prisma.XOR<Prisma.PropertyUpdateManyMutationInput, Prisma.PropertyUncheckedUpdateManyInput>
  /**
   * Filter which Properties to update
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to update.
   */
  limit?: number
}

/**
 * Property upsert
 */
export type PropertyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * The filter to search for the Property to update in case it exists.
   */
  where: Prisma.PropertyWhereUniqueInput
  /**
   * In case the Property found by the `where` argument doesn't exist, create a new Property with this data.
   */
  create: Prisma.XOR<Prisma.PropertyCreateInput, Prisma.PropertyUncheckedCreateInput>
  /**
   * In case the Property was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PropertyUpdateInput, Prisma.PropertyUncheckedUpdateInput>
}

/**
 * Property delete
 */
export type PropertyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  /**
   * Filter which Property to delete.
   */
  where: Prisma.PropertyWhereUniqueInput
}

/**
 * Property deleteMany
 */
export type PropertyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Properties to delete
   */
  where?: Prisma.PropertyWhereInput
  /**
   * Limit how many Properties to delete.
   */
  limit?: number
}

/**
 * Property.billings
 */
export type Property$billingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Billing
   */
  select?: Prisma.BillingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Billing
   */
  omit?: Prisma.BillingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BillingInclude<ExtArgs> | null
  where?: Prisma.BillingWhereInput
  orderBy?: Prisma.BillingOrderByWithRelationInput | Prisma.BillingOrderByWithRelationInput[]
  cursor?: Prisma.BillingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BillingScalarFieldEnum | Prisma.BillingScalarFieldEnum[]
}

/**
 * Property.maintenances
 */
export type Property$maintenancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Maintenance
   */
  select?: Prisma.MaintenanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Maintenance
   */
  omit?: Prisma.MaintenanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MaintenanceInclude<ExtArgs> | null
  where?: Prisma.MaintenanceWhereInput
  orderBy?: Prisma.MaintenanceOrderByWithRelationInput | Prisma.MaintenanceOrderByWithRelationInput[]
  cursor?: Prisma.MaintenanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MaintenanceScalarFieldEnum | Prisma.MaintenanceScalarFieldEnum[]
}

/**
 * Property.feedbacks
 */
export type Property$feedbacksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Feedback
   */
  select?: Prisma.FeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Feedback
   */
  omit?: Prisma.FeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackInclude<ExtArgs> | null
  where?: Prisma.FeedbackWhereInput
  orderBy?: Prisma.FeedbackOrderByWithRelationInput | Prisma.FeedbackOrderByWithRelationInput[]
  cursor?: Prisma.FeedbackWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FeedbackScalarFieldEnum | Prisma.FeedbackScalarFieldEnum[]
}

/**
 * Property.users
 */
export type Property$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Users
   */
  select?: Prisma.UsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Users
   */
  omit?: Prisma.UsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersInclude<ExtArgs> | null
  where?: Prisma.UsersWhereInput
  orderBy?: Prisma.UsersOrderByWithRelationInput | Prisma.UsersOrderByWithRelationInput[]
  cursor?: Prisma.UsersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * Property without action
 */
export type PropertyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
}
