
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Users
 * 
 */
export type Users = Prisma.UsersModel
/**
 * Model Property
 * 
 */
export type Property = Prisma.PropertyModel
/**
 * Model Expenses
 * 
 */
export type Expenses = Prisma.ExpensesModel
/**
 * Model Billing
 * 
 */
export type Billing = Prisma.BillingModel
/**
 * Model Maintenance
 * 
 */
export type Maintenance = Prisma.MaintenanceModel
/**
 * Model Documentation
 * 
 */
export type Documentation = Prisma.DocumentationModel
/**
 * Model Feedback
 * 
 */
export type Feedback = Prisma.FeedbackModel
/**
 * Model Messages
 * 
 */
export type Messages = Prisma.MessagesModel
/**
 * Model Resource
 * 
 */
export type Resource = Prisma.ResourceModel
