
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Users'
export type * from './models/Property'
export type * from './models/Expenses'
export type * from './models/Billing'
export type * from './models/Maintenance'
export type * from './models/Documentation'
export type * from './models/Feedback'
export type * from './models/Messages'
export type * from './models/Resource'
export type * from './commonInputTypes'