
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Users: 'Users',
  Property: 'Property',
  Expenses: 'Expenses',
  Billing: 'Billing',
  Maintenance: 'Maintenance',
  Documentation: 'Documentation',
  Feedback: 'Feedback',
  Messages: 'Messages',
  Resource: 'Resource'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UsersScalarFieldEnum = {
  userID: 'userID',
  username: 'username',
  password: 'password',
  role: 'role',
  firstName: 'firstName',
  lastName: 'lastName',
  middleInitial: 'middleInitial',
  sex: 'sex',
  bday: 'bday',
  propertyId: 'propertyId',
  email: 'email',
  firstNumber: 'firstNumber',
  secondNumber: 'secondNumber',
  created_at: 'created_at',
  hasLeftProperty: 'hasLeftProperty',
  leftDate: 'leftDate'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const PropertyScalarFieldEnum = {
  propertyId: 'propertyId',
  name: 'name',
  rent: 'rent',
  area: 'area',
  yearBuilt: 'yearBuilt',
  renovated: 'renovated',
  address: 'address',
  description: 'description',
  createdAt: 'createdAt'
} as const

export type PropertyScalarFieldEnum = (typeof PropertyScalarFieldEnum)[keyof typeof PropertyScalarFieldEnum]


export const ExpensesScalarFieldEnum = {
  expensesID: 'expensesID',
  paidRent: 'paidRent',
  paidWater: 'paidWater',
  paidElectric: 'paidElectric',
  datePaid: 'datePaid'
} as const

export type ExpensesScalarFieldEnum = (typeof ExpensesScalarFieldEnum)[keyof typeof ExpensesScalarFieldEnum]


export const BillingScalarFieldEnum = {
  billingID: 'billingID',
  userID: 'userID',
  propertyId: 'propertyId',
  totalRent: 'totalRent',
  totalWater: 'totalWater',
  totalElectric: 'totalElectric',
  dateIssued: 'dateIssued'
} as const

export type BillingScalarFieldEnum = (typeof BillingScalarFieldEnum)[keyof typeof BillingScalarFieldEnum]


export const MaintenanceScalarFieldEnum = {
  maintenanceID: 'maintenanceID',
  userID: 'userID',
  propertyId: 'propertyId',
  rawRequest: 'rawRequest',
  processedRequest: 'processedRequest',
  status: 'status',
  schedule: 'schedule',
  dateIssued: 'dateIssued'
} as const

export type MaintenanceScalarFieldEnum = (typeof MaintenanceScalarFieldEnum)[keyof typeof MaintenanceScalarFieldEnum]


export const DocumentationScalarFieldEnum = {
  docuID: 'docuID',
  maintenanceID: 'maintenanceID',
  documentation: 'documentation',
  dateIssued: 'dateIssued'
} as const

export type DocumentationScalarFieldEnum = (typeof DocumentationScalarFieldEnum)[keyof typeof DocumentationScalarFieldEnum]


export const FeedbackScalarFieldEnum = {
  feedbackID: 'feedbackID',
  name: 'name',
  propertyId: 'propertyId',
  userID: 'userID',
  ratings: 'ratings',
  message: 'message',
  dateIssued: 'dateIssued'
} as const

export type FeedbackScalarFieldEnum = (typeof FeedbackScalarFieldEnum)[keyof typeof FeedbackScalarFieldEnum]


export const MessagesScalarFieldEnum = {
  messageID: 'messageID',
  senderID: 'senderID',
  receiverID: 'receiverID',
  message: 'message',
  dateSent: 'dateSent'
} as const

export type MessagesScalarFieldEnum = (typeof MessagesScalarFieldEnum)[keyof typeof MessagesScalarFieldEnum]


export const ResourceScalarFieldEnum = {
  resourceId: 'resourceId',
  referenceId: 'referenceId',
  referenceType: 'referenceType',
  url: 'url',
  fileName: 'fileName',
  createdAt: 'createdAt'
} as const

export type ResourceScalarFieldEnum = (typeof ResourceScalarFieldEnum)[keyof typeof ResourceScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UsersOrderByRelevanceFieldEnum = {
  username: 'username',
  password: 'password',
  role: 'role',
  firstName: 'firstName',
  lastName: 'lastName',
  middleInitial: 'middleInitial',
  sex: 'sex',
  email: 'email',
  firstNumber: 'firstNumber',
  secondNumber: 'secondNumber'
} as const

export type UsersOrderByRelevanceFieldEnum = (typeof UsersOrderByRelevanceFieldEnum)[keyof typeof UsersOrderByRelevanceFieldEnum]


export const PropertyOrderByRelevanceFieldEnum = {
  name: 'name',
  address: 'address',
  description: 'description'
} as const

export type PropertyOrderByRelevanceFieldEnum = (typeof PropertyOrderByRelevanceFieldEnum)[keyof typeof PropertyOrderByRelevanceFieldEnum]


export const MaintenanceOrderByRelevanceFieldEnum = {
  rawRequest: 'rawRequest',
  processedRequest: 'processedRequest',
  status: 'status'
} as const

export type MaintenanceOrderByRelevanceFieldEnum = (typeof MaintenanceOrderByRelevanceFieldEnum)[keyof typeof MaintenanceOrderByRelevanceFieldEnum]


export const DocumentationOrderByRelevanceFieldEnum = {
  documentation: 'documentation'
} as const

export type DocumentationOrderByRelevanceFieldEnum = (typeof DocumentationOrderByRelevanceFieldEnum)[keyof typeof DocumentationOrderByRelevanceFieldEnum]


export const FeedbackOrderByRelevanceFieldEnum = {
  name: 'name',
  message: 'message'
} as const

export type FeedbackOrderByRelevanceFieldEnum = (typeof FeedbackOrderByRelevanceFieldEnum)[keyof typeof FeedbackOrderByRelevanceFieldEnum]


export const MessagesOrderByRelevanceFieldEnum = {
  message: 'message'
} as const

export type MessagesOrderByRelevanceFieldEnum = (typeof MessagesOrderByRelevanceFieldEnum)[keyof typeof MessagesOrderByRelevanceFieldEnum]


export const ResourceOrderByRelevanceFieldEnum = {
  referenceType: 'referenceType',
  url: 'url',
  fileName: 'fileName'
} as const

export type ResourceOrderByRelevanceFieldEnum = (typeof ResourceOrderByRelevanceFieldEnum)[keyof typeof ResourceOrderByRelevanceFieldEnum]

